### ISSUE TITLE
Flag personally identifiable information in dbt docs

### ISSUE THREAD

**Issue by jgillies** [fishtown-analytics/dbt#1008]
### Feature description
Add ability to flag PII-containing fields and/or models in dbt documentation

### Who will this benefit?
Anyone needing to deal with PII handling responsibilities

**Comment by drewbanin** [comment]
Thanks for the feature request @jgillies! We currently surface schema tests in the report, though it would be really great to also surface _attributes_ of columns, including (but not limited to) their status as PII.

That interface currently looks like this:
<img width="766" alt="screen shot 2018-09-17 at 4 41 51 pm" src="https://user-images.githubusercontent.com/1541139/45649217-b5a3b400-ba98-11e8-833b-c6fd85892e4e.png">

Are you imagining that you'd tag these columns as PII in `schema.yml`? It might be compelling to add another field to `schema.yml` for `properties` that looks something like this:
```
version: 2

models:
  - name: some_model

    columns:
        - name: customer_name
          properties:
              - pii
          tests:
              - not_null
```

A property like that could flow through to the documentation website, for instance
