### ISSUE TITLE
Tests that fail with 1 error report "True" instead of "1" for the number of errors

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1040]
### Issue description
Tests that fail with 1 error report "True" instead of "1" for the number of errors. This happens, I think, because we fetch an Agate dataframe, which assumes that the number of failures is a boolean instead of an integer.

### Results
Expected: [FAIL 1]
Received: [Fail True]

### System information
>= 0.11.1

The python version you're using (probably the output of `python --version`)
3.7

### Steps to reproduce

```
-- models/test_model.sql

select null as id

```

```
# schema.yml

version: 2

models:
  - name: test_model:
  - columns:
    name: id
    tests:
      - not_null
```
