### ISSUE TITLE
0.12.0 alpha: less restrictive validation

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1078]
dbt v0.12.0a-1 has overly restrictive type checks:

**1. Invalid arguments passed to "Project" instance: models.None is not of type 'object'**

This happens when the `models:` block in `dbt_project.yml` is left empty. I imagine the same will apply to the `seeds:` block? If no value is supplied for these configs, they should be treated as empty dictionaries.

```
# dbt_project.yml
# This doesn't currently work (but it should):

models:

seeds:
```

```
# dbt_project.yml
# This _does_ work

models: {}

seeds: {}
```

**2.   Invalid arguments passed to "GitPackage" instance: revision.['0.1.12', '0.1.12'] is not of type 'string'**

This comes from a `packages.yml` file when running `dbt deps`.

```
packages:
  - git: https://github.com/fishtown-analytics/dbt-utils.git
    revision: 0.1.12
  - git: https://github.com/fishtown-analytics/bing-ads.git
    revision: 0.1.1
  - git: https://github.com/fishtown-analytics/facebook-ads.git
    revision: 0.3.2
  - git: https://github.com/fishtown-analytics/adwords.git
    revision: 0.2.2
  - git: https://github.com/fishtown-analytics/dbt-event-logging.git
    revision: 0.1.5
```

^ This packages.yml looks pretty reasonable to me. If it turns out that this was indeed a simple regression, we should also add a test!
