### ISSUE TITLE
Incorrect package duplicate error when using/missing .git extension

### ISSUE THREAD

**Issue by DylanBaker** [fishtown-analytics/dbt#1084]
### Issue description
dbt seems to treat packages as not identical (but with duplicate name) if one reference has the `.git` file extension and another does not. This is problematic when adding a dependency that uses a package a project already includes.

### Results
I had a project that was pulling the `dbt-utils` package. When I set up the `dbt-event-logging` package, despite pulling the same version/release, dbt returned the following error:
```
Found duplicate project dbt_utils. 
This occurs when a dependency has the same project name as some other dependency.
```
My `packages.yml` looked like:
```
packages:
  - git: "https://github.com/fishtown-analytics/dbt-utils"
    revision: 0.1.12

  - git: "https://github.com/fishtown-analytics/dbt-event-logging.git"
    revision: 0.1.5
```
The `package.yml` file in dbt-event-logging looks like:
```
packages:
  - git: "https://github.com/fishtown-analytics/dbt-utils.git"
    revision: 0.1.12
```
The problem was resolved by adding the `.git` suffix to the dbt-utils package in my project. 

### System information
The output of `dbt --version`:
```
installed version: 0.10.1
   latest version: 0.11.1
```

The operating system you're running on: Windows

The python version you're using: 3.6.0
