### ISSUE TITLE
Support more intuitive keys in profiles.yml file

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/dbt#1165]
### Feature description
Currently the structure of a profile is:
```yaml
jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      ...
```

For me, the more intuitive labels would be:
* ~target~ -> `default`
* ~outputs~ -> `targets`
```yaml
jaffle_shop:
  default: dev
  targets:
    dev:
      type: postgres
      ...
```

**Comment by clrcrl** [comment]
Related suggestion is to make the structure more like the scheam v2 structure:
```yaml
version: 2

profiles:
  - name: jaffle_shop
    default: dev
    targets:
      - name: dev
        type: postgres
        host: localhost
        ...
```
