### ISSUE TITLE
Support SSO authentication for Snowflake

### ISSUE THREAD

**Issue by adriank-convoy** [fishtown-analytics/dbt#1172]
### Feature description
Snowflake support SSO through SAML 2.0 compliant identity providers, allowing companies to manage access to Snowflake without provisioning accounts with passwords for each employee. The feature request is to enable the external browser authentication provided by the official Snowflake python connector when using dbt.

https://docs.snowflake.net/manuals/user-guide/python-connector-example.html#connecting-using-federated-authentication

Based on the options of the above Snowflake connector, the profile might look something like:

```
[profile-name]:
  outputs:
    external_browser_example:
      type: snowflake
      threads: [1 - 8]
      account: [url prefix for your snowflake connection]

      user: [user]
      authenticator: 'externalbrowser'
      role: [optional, the snowflake role you want to use]

      database: [db name]
      warehouse: [warehouse]
      schema: [schema name]
    native_okta_example:
      type: snowflake
      threads: [1 - 8]
      account: [url prefix for your snowflake connection]

      user: [okta_user]
      passwprd: [okta_password]
      authenticator: 'https://<okta_accout_name>.okta.com/'
      role: [optional, the snowflake role you want to use]

      database: [db name]
      warehouse: [warehouse]
      schema: [schema name]
  target: [target-name]
```

### Who will this benefit?
Any company using SSO to manage employee access to resources, specifically Okta. We'd really like to avoid managing a separate set of credentials for Snowflake as our company grows. Having tried out the external browser authentication in a few python scripts, it's pretty slick.
