### ISSUE TITLE
Type coercion for profiles.yml fields

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1259]
via @cabouffard (originally opened [here](https://github.com/fishtown-analytics/dbt-utils/issues/108))

Hey, 

I’m hitting some kind of unexpected errors. I want the `thread` value of my `profiles.yml` file to be configurable via ENV variables, such as I can do the following:

```
default:
  outputs:
    dev:
      type: redshift
      threads: "{{ env_var('DEV_DBT_THREADS') }}" # [1-8]
      host: "{{ env_var('DEV_WAREHOUSE_DB_HOST') }}"
      port: "{{ env_var('DEV_WAREHOUSE_DB_PORT') }}"
      user: "{{ env_var('DEV_WAREHOUSE_DB_USER') }}"
      pass: "{{ env_var('DEV_WAREHOUSE_DB_PASSWORD') }}"
      dbname: "{{ env_var('DEV_WAREHOUSE_DB_NAME') }}"
      schema: "{{ env_var('DEV_DBT_SCHEMA_OUTPUT') }}"
    staging:
      type: redshift
      threads: "{{ env_var('STAGING_DBT_THREADS') }}" # [1-8]
      host: "{{ env_var('STAGING_WAREHOUSE_DB_HOST') }}"
      port: "{{ env_var('STAGING_WAREHOUSE_DB_PORT') }}"
      user: "{{ env_var('STAGING_WAREHOUSE_DB_USER') }}"
      pass: "{{ env_var('STAGING_WAREHOUSE_DB_PASSWORD') }}"
      dbname: "{{ env_var('STAGING_WAREHOUSE_DB_NAME') }}"
      schema: "{{ env_var('STAGING_DBT_SCHEMA_OUTPUT') }}"
    production:
      type: redshift
      threads: "{{ env_var('PRODUCTION_DBT_THREADS') }}" # [1-8]
      host: "{{ env_var('PRODUCTION_WAREHOUSE_DB_HOST') }}"
      port: "{{ env_var('PRODUCTION_WAREHOUSE_DB_PORT') }}"
      user: "{{ env_var('PRODUCTION_WAREHOUSE_DB_USER') }}"
      pass: "{{ env_var('PRODUCTION_WAREHOUSE_DB_PASSWORD') }}"
      dbname: "{{ env_var('PRODUCTION_WAREHOUSE_DB_NAME') }}"
      schema: "{{ env_var('PRODUCTION_DBT_SCHEMA_OUTPUT') }}"
  target: "{{ env_var('DBT_TARGET') }}"
```

Unfortunately, when building the docs I’m raised with the following error:

```
pipeline-dbt-docs | Encountered an error while reading profiles:
pipeline-dbt-docs |   ERROR Runtime Error
pipeline-dbt-docs |   Runtime Error
pipeline-dbt-docs |     Invalid arguments passed to "ProfileConfig" instance: threads.'4' is not of type 'number'
pipeline-dbt-docs | Defined profiles:
pipeline-dbt-docs |  - default
```

I dug a little bit, and saw that `env_var` was a macro defined by [this](https://github.com/fishtown-analytics/dbt/blob/dcc017d681c3e0a84555846f60db9443246ea206/dbt/context/common.py#L155) that uses `os.environ`. In this context, `os.environ` will always return a string.

I then dug into how the validation was being done and found [this](https://github.com/fishtown-analytics/dbt/blob/dcc017d681c3e0a84555846f60db9443246ea206/dbt/contracts/project.py#L314 ) which expects the value to be a number.

I'm unsure how to properly resolve that other than currently hard-coding a value to something.

I wanted to flag and document this error as this seems to be something that should be fixed.
Thanks!

**Comment by drewbanin** [comment]
I think the big problem here is that Jinja will _always_ render out values as strings. While environment variables will be stringy in nature, there's a world in which something like this _could_ work:

```
default:
  outputs:
    dev:
      type: redshift
      threads: "{{ env_var('DEV_DBT_THREADS')| int }}"
      ....
```

^ note the pipe through the `int` filter. This will take a stringy env var (`DEV_DBT_THREADS`), coerce it to an int, then coerce is _back_ to a string when it's being rendered in the Jinja environment. One option we may have here is to use a [jinja native environment](http://jinja.pocoo.org/docs/2.10/nativetypes/). I'm not positive I love this feature, but it seems like it exists for this usecase:
> With NativeEnvironment, rendering a template produces a native Python type

Outside of `threads` and `port`, this also impacts folks that want to set a dbt `var` via an `env_var`. Eg:
```
models:
  vars:
    lookback_days: "{{ var('lookback_days', env_var("DEFAULT_LOOKBACK_DAYS", 7)) }}"
```

^ contrived example, but this will _always_ return a string type, and the user of the var will need to coerce it appropriately.

**Comment by beckjake** [comment]
That's a great point! What about providing a flag to env_var and injecting some parameter candidates into the rendering context wherever we use `env_var`?

```
default:
  outputs:
    dev:
      type: redshift
      threads: "{{ env_var('DEV_DBT_THREADS', 3, cast=cast.INTEGER) }}"
      ....
```
