### ISSUE TITLE
Strict mode does nothing

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#1279]
## Issue
dbt's `--strict` flag does nothing!

### Issue description
If you use the `--strict` flag to dbt, it will do nothing. The `--strict` flag is never examined by dbt. Strict mode runs that should emit errors emit warnings instead.

I think this issue is at least somewhat related to #1243, since `--strict` is kind of a super-`werror` flag. Also, we have this idea that we're getting value by passing `--strict` for all integration test runs, but we aren't actually... oops.

### System information
dbt version: 0.12.2, though this issue predates it

The operating system you're running on:
Any

The python version you're using (probably the output of `python --version`)
Any

### Steps to reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example models, etc are all very helpful here.

Run dbt with something that should trigger 'strict mode' and use the `--strict` mode. One example would be to create a malformed test definition in a schema.yml file, like this:

```
models:
  - name: table_copy
    columns:
      - name: favorite_color
        tests:
          # this is missing a "-" and is malformed
          accepted_values: { values: ['blue', 'green'] }
```

`dbt  --strict compile` should fail with an error here, but it won't, instead it emits warnings.
