### ISSUE TITLE
Doing snowflake snapshot via dbt archive 

### ISSUE THREAD

**Issue by yennanliu** [fishtown-analytics/dbt#1331]
## Issue
Try running abt archive on the snowflake, but it only archives the last day data 

### Issue description
Running abt archive on the snowflake, but it only archives the last day data 
But what I want to do is : `running abt archive every day  and keep all table 
snapshot history in the db`

the dbt command is sth like below :  

```
EXECUTION_DATE=2019-01-01  dbt archive  --profiles-dir=<profiles-dir>     --profiles-dir .
```
the dbt_project.yml archive setting  is like this  :  
```

archive:

    - source_schema: my_schema  
      target_schema: my_archive_schema  
      tables:
      - source_table: my_table
        target_table: my_archive_table
        updated_at: RECORDED_AT::TIMESTAMP
        unique_key: RECORDED_AT::TIMESTAMP || PARTNER_ID
```

### Results
There is only last day data archived in the snowflake 
e.g. 
```
dbt archive table on 2019-01-01 --> snowflake table only has 2019-01-01 data
dbt archive table on 2019-01-02 --> snowflake table only has 2019-01-02 data
dbt archive table on 2019-01-03 --> snowflake table only has 2019-01-03 data
.
.
.
```

### System information
The output of `dbt --version`:
```
installed version: 0.12.2
   latest version: 0.12.2
```

The operating system you're running on:
```
Mac OSX Mojave
```

The python version you're using (probably the output of `python --version`)

```
Python 3.5.4 :: Anaconda, Inc.
```

### Who will this benefit?
People who want to use dbt archive doing db snapshots

**Comment by drewbanin** [comment]
hey @yennanliu - thanks for the report. The behavior you're seeing is definitely not intended. 

Are you able to tell me a little more about the source table you're archiving?
- Are `RECORDED_AT` or `PARTNER_ID` ever null?
- Does the `RECORDED_AT` value change for a record when new data is loaded?

You said:
> There is only last day data archived in the snowflake

Do you find that that data from previous days is _deleted_ from the archive table?

dbt's Archival functionality should _never_ delete data from the target table, but should instead modify the `valid_from` and `valid_to` dates for records when the source data changes. Are you able to check these `valid_from` and `valid_to` columns and determine if they are are being set appropriately?

Thanks for your help here -- these questions will help me reproduce this behavior locally. Let me know!

**Comment by yennanliu** [comment]
Hi @drewbanin 

1 )  The RECORDED_AT and  PARTNER_ID are not null data in general, here is the sample :
```
Row  RECORDED_AT                           PARTNER_ID
1      2019-01-01 06:03:19.000            10000
2      2019-01-02 06:03:19.000           10001
3      2019-01-03 06:03:19.000           10002
```

2)  No, `RECORDED_AT ` just means the timestamp the data was created. that record of that  column should be unchanged when new data is loaded 


3)  In my cases, `valid_from` is always as same as the `RECORDED_AT` 
( as the  archive setting in dbt_project.yml) ;   and `valid_to` is always `Null`
below is part of the sql when running dbt archive I think would be the key of this operation?


```
insertions as (

        select
            current_data.*,
            null::TIMESTAMP as "valid_to"
        from current_data
        left outer join archived_data
          on archived_data."dbt_pk" = current_data."dbt_pk"
        where archived_data."dbt_pk" is null or (
          archived_data."dbt_pk" is not null and
          current_data."dbt_updated_at" > archived_data."dbt_updated_at" and
          archived_data."tmp_valid_to" is null
        )
    ),

    updates as (

        select
            archived_data.*,
            current_data."dbt_updated_at" as "valid_to"
        from current_data
        left outer join archived_data
          on archived_data."dbt_pk" = current_data."dbt_pk"
        where archived_data."dbt_pk" is not null
          and archived_data."dbt_updated_at" < current_data."dbt_updated_at"
          and archived_data."tmp_valid_to" is null
    )
```

**Comment by drewbanin** [comment]
Ok - i think part of this sounds right to me. If you're using the `RECORDED_AT` as the `updated_at` field, and `RECORDED_AT` is indeed immutable, then dbt will _never_ set a `valid_to` date for the archived records! 

Is there some other timestamp you can use (like an `updated_at`) that will signify that a record has changed? The alternative would be using something like `current_timestamp()` as the `updated_at` to _always_ snapshot the entirety of the table every time archival runs. I'm not sure if that's appropriate for your use case, but I wanted to put it out there as a possibility.

Beyond these things, I'm still stumped by this part of your original issue comment:
```
There is only last day data archived in the snowflake, e.g.

dbt archive table on 2019-01-01 --> snowflake table only has 2019-01-01 data
dbt archive table on 2019-01-02 --> snowflake table only has 2019-01-02 data
dbt archive table on 2019-01-03 --> snowflake table only has 2019-01-03 data
```

The snippet you pasted in is indeed the core part of dbt's archival functionality. dbt uses this query to generate a temporary table, then it runs an `update` and an `insert` statement to "merge" the new archive snapshot into the destination table. I can't really imagine how dbt could be _deleting_ records from the destination table.

Can you say more about how you're determining that "There is only last day data archived in the snowflake"? What kind of query are you running to determine that this is indeed the case?

**Comment by yennanliu** [comment]
Hey @drewbanin 

* There are only 2 timestamp columns in that table: `_INSERTED_AT`, and `RECORDED_AT`
and all records are all the same within that 2 columns 


* So how do I check there is only last data archived in the snowflake is :   

via this  query :  
```
select DISTINCT(RECORDED_AT::DATE) from DATAWAREHOUSE ;
```
then I will be able to see how many data with discrete RECORDED_AT is archived in the table

**Comment by drewbanin** [comment]
ok, I'm unsure if this is a typo or not, but you'd actually want to be querying `datawarehouse.my_archive_schema.my_archive_table`, right?

It would be helpful if you could share the actual values in the archive section of your `dbt_project.yml` file, as well as the contents of the debug queries that you're actually running!

**Comment by yennanliu** [comment]
Hi @drewbanin  

Sorry for the typo. the query is `datawarehouse.my_archive_schema.my_archive_table`  
thanks for point that out.


The setting of our `dbt_project.yml` is like below :  


```
name: 'my_dbt_project'
version: '1.0'

profile: 'my_project'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]


log-path: "/tmp/log"
target-path: "/tmp/target"  
clean-targets:         
- "/tmp/target"
- "/tmp/dbt_modules"

quoting:
  identifier: false
  schema: false

models:
  materialized: view
  pre-hook: "{{ logging.log_model_start_event() }}"
  post-hook: "{{ logging.log_model_end_event() }}"


archive:

    - source_schema: my_schema  
      target_schema: my_archive_schema  
      tables:
      - source_table: my_table
        target_table: my_archive_table
        updated_at: RECORDED_AT::TIMESTAMP
        unique_key: RECORDED_AT::TIMESTAMP || PARTNER_ID


seeds:
  my_dbt:
    enabled: true
    schema: seed_data

on-run-end:
    - 'grant usage on schema "{{ target.schema }}" to PUBLIC'
    - 'grant select, references on all tables in schema "{{ target.schema }}" to PUBLIC'
```

The debug query I used like below  : 

```
SELECT  RECORDED_AT::DATE, count(*) FROM  DATAWAREHOUSE.my_schema.my_table
GROUP BY 1 ORDER BY 1  ;

```
