### ISSUE TITLE
Feature: Configurable, forced WHERE clause for Sources

### ISSUE THREAD

**Issue by MartinGuindon** [fishtown-analytics/dbt#1365]
### Feature description
Following the introduction of Sources in 0.13.0 (_which is an awesome feature!_), I would very much like to be able to configure an unconditional `WHERE` clause in the source configuration, similar to the `sql_always_where` function in Looker.

For example:

```yml
sources:
  - name: foobar
    database: raw
    schema: foobar
    loader: fivetran
    sql_always_where: "_fivetran_deleted = false"
```

When compiling, dbt would add or merge the WHERE statement based on the statement in sources.yml within source() references.

### Who will this benefit?
Any dbt developer working with a source in which they need to unconditionally filter out rows (such as deleted rows) in every single table they're using in that particular source.

For example, every reference to my main data source now looks like this:
```sql
WITH source AS (
  SELECT *
  FROM {{ source('foobar', 'some_table') }}
  WHERE _fivetran_deleted = false
)
```

Two core benefits:
- Increase the dryness of code in the models
- Reduce the risk of errors as one might forget to include the statement in a particular model
