### ISSUE TITLE
Feature: Dynamic Schemas / Columns

### ISSUE THREAD

**Issue by jars** [fishtown-analytics/dbt#1374]
# Feature: Dynamic Schemas / Columns

Problem:

- unable to eliminate similar `schema.yml`'s by abstracting their contents into a callable file/macro.
- this issue [originally raised in dbt Slack](https://getdbt.slack.com/archives/C2JRRQDTL/p1553397773406500)

To illustrate, here's a artificial example. Assume I have a models already called `dog` and `cat`.

Also assume that the SQL required to query any animal type is very complex and is worthy of needing a macro for DRY reasons. Then, we would have a macro like:

##### `macros/pet.sql`:
```twig
{% macro pet(type) %}
  SELECT * FROM {{ref(type)}} 
  WHERE im_actually_a_super_complex_macro_needing_sql_statement IS TRUE
{% endmacro %}
```

And we would express our models like:

##### `models/dog.sql`:
```twig
{{ pet("dog") }}
```

##### `models/cat.sql`:
```twig
{{ pet("cat")
```

And finally, our schemas like:

##### `models/dog.yml`:
```yml
version: 2
models:
  - name: dog
    columns:
        - name: name
          description: 'the name of the dog'
        - name: age
          description: 'the age of the dog'
        - name: breed
          description: 'the breed of the dog'
```

##### `models/cat.yml`:
```yml
version: 2
models:
  - name: cat
    columns:
        - name: name
          description: 'the name of the cat'
        - name: age
          description: 'the age of the cat'
        - name: breed
          description: 'the breed of the cat'
```

Again, this is a contrived example, but the problem is magnified in larger projects. i.e. Both `dog.yml` and `cat.yml` files are nearly identical except the animal type. Leading to WET code.

----

## Some Possible Solutions:

1. Allow `schema.yml` files to be macroable:

##### `models/dog.yml`:
```twig
{{ schema_pet("dog") }}
```

##### `models/cat.yml`:
```twig
{{ schema_pet("cat") }}
```

##### `macros/schema_pet.yml`
```yml
{% macro schema_pet(type) %}
version: 2
models:
  - name: {{ type }}
    columns:
        - name: name
          description: 'the name of the {{ type }}'
        - name: age
          description: 'the age of the {{ type }}'
        - name: breed
          description: 'the breed of the {{ type }}'
{% endmacro %}
```

In this situation, the model may not know which schema belonged to it (barring file name parsing), so the models would also need to specify, I believe:

##### `models/dog.sql`:
```twig
{{ config(schema = 'dog') }}
{{ pet("dog") }}
```

##### `models/cat.sql`:
```twig
{{ config(schema = 'cat') }}
{{ pet("cat") }}
```

----

2. Actually, the majority of the duplication occurs in the columns section of the yml file. I believe introducing a dynamic `models.name` parameter inside the schema.yml will cause a lot of complications, so even if this was static, but the rest of the file could be dynamic, this would be great. 

##### `macros/pet_columns.yml`
```twig
{% macro pet_columns(type) %}
- name: name
  description: 'the name of the {{ type }}'
- name: age
  description: 'the age of the {{ type }}'
- name: breed
  description: 'the breed of the {{ type }}'
{% endmacro %}
```

##### `models/dog.yml`
```yml
version: 2
models:
  - name: dog
    columns: {{ pet_columns('dog') }}
```

##### `models/cat.yml`
```yml
version: 2
models:
  - name: cat
    columns: {{ pet_columns('cat') }}
```

The `doc` macro would be great for this too, however it's not possible to provide args to the docs/doc macro.

Forgive me if some of my suggestions are incompatible with the current dbt structure. I am new, and not familiar with how the internals work. These are only suggestions, and I welcome the feedback from the dbt masters!
