### ISSUE TITLE
Support `generate_source_name` macro

### ISSUE THREAD

**Issue by dcaribou** [fishtown-analytics/dbt#1390]
### Feature description
Currently sources relation name is built by simply concatenating the schema and table name (or the identifier). Default schema can be overridden, but the name building behavior is fixed. Instead support a `generate_source_name` macro that can be overridden with custom behavior. Default macro in `global_project` would look like:

```
{% macro generate_source_name(schema, table_name) -%}
{{ schema ~ '.' ~ table_name  }}
{%- endmacro %}
```

But it could be overridden dropping a file in your `macros` folder. 
Say there are two loaders `ldrA` and `ldrB`, each loading two tables `tblA` and `tblB`. Both loaders will copy their tables into the same `raw` schema, adding a prefix to the table name to identify the loader. So `ldrA` will load his tables as `ldrA_tblA` and `ldrA_tblB` and `ldrB` will load them as `ldrB_tblA` and `ldrB_tblB`. I want to be able to define my `sources` section as:

```yaml
sources:
 - name: ldrA
    schema: raw
    tables:
      - name: tblA
      - name: tblB
 - name: ldrB
    schema: raw
    tables:
      - name: tblA
      - name: tblB
```
And overwrite the default behavior with a `generate_source_name` macro in my dbt project with
```
{% macro generate_source_name(schema, table_name) -%}
{# somehow the 'source' object would have to be added in the jinja context #}
{% set source_name = source.name %}
{{ schema ~ '.' ~ source_name ~ '_' ~ table_name  }}
{%- endmacro %}
```
So the correct table name is picked up by the source.

### Who will this benefit?
DBT user who want to use sources but the naming pattern for the tables being loaded by loaders does not match the standard.
