### ISSUE TITLE
Should the built-in `relationships` schema test return the number of unique unmatched records? 

### ISSUE THREAD

**Issue by clausherther** [fishtown-analytics/dbt#1444]
If I add a relationship test in a `schema.yml` file to check whether dimension keys in a fact table match the dimension keys in the relation dimension, the test returns the number of _fact table_ rows that are not matched to a dimension key in the dimension.

E.g. let's assume dimension table called `d_sku` and we add a test to `f_orders` model to test the relationship on `sku_key`:
```
version: 2

models:
    - name: f_orders
      columns:
          - name: sku_key
            tests:
                - not_null
                - relationships:
                    to: ref('d_sku')
                    field: sku_key
```
Let's say only one `sku_key` in `f_order` was not in `d_sku` but this `sku_key` was in 100 rows in `f_orders`, the output of the test would be

```
Failure in test relationships_f_orders_sku_key__sku_key__ref_d_sku_ (models/_schema/f_orders.yml)
  Got 100 results, expected 0.
```

Would a result of `Got 1 results, expected 0` be more helpful here?
