### ISSUE TITLE
Bigquery: Enable User to Choose Job Priority in Profile

### ISSUE THREAD

**Issue by davidjinlee** [fishtown-analytics/dbt#1456]
### Feature description
This would allow users to define the `job priority` (batch vs interactive) in their Bigquery profile. When a model is run using the profile with the job priority defined as "batch", DBT would block until the query is actually executed. This would allow for 

The benefits of having ability to define the job priority:

1. Allows users to queue up their jobs
2. Lets users run lower priority queries without impacting higher priority ones
3. Does not count towards concurrency quota

**Comment by drewbanin** [comment]
Hey @davidjinlee - cool idea! Every query that dbt executes on BQ should go through the [raw_execute()](https://github.com/fishtown-analytics/dbt/blob/dev/wilt-chamberlain/plugins/bigquery/dbt/adapters/bigquery/connections.py#L187-L201) method. I think this will be the place to add this config. 

The [BQ docs](https://cloud.google.com/bigquery/docs/running-queries#batch) seem to indicate that job priority can be configured with:
```
job_config = bigquery.QueryJobConfig()
job_config.priority = bigquery.QueryPriority.BATCH
```

We should be able to add a `priority` key to the profile config. That might look like:
```yml
my-profile:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: '....'
      priority: batch # one of batch|interactive, if provided
```

Then from the `raw_execute` method, we can access this config with:
```
priority = conn.credentials.get('priority', 'interactive')
```

How does all of that sound?
