### ISSUE TITLE
Allow partition filters to be passed to source freshness checks

### ISSUE THREAD

**Issue by whittid4** [fishtown-analytics/dbt#1495]
### Allow partition filters to be passed to source freshness checks 
If the source table has a mandatory partition filter (as BigQuery offers) then the out-of-the-box freshness check will fail since the partition filter cannot be passed to the SQL query.

`Cannot query over table 'prod.core.stock' without a filter over column(s) 'date' that can be used for partition elimination`

This is because the query generated from the freshness check runs the following:

```
select
      max(date) as max_loaded_at,
      CURRENT_TIMESTAMP() as snapshotted_at
    from `prod`.`core`.`stock`
```

### Who will this benefit?
This feature would benefit users who have mandatory partitions applied to tables. It is currently an issue with BigQuery, but would apply to any source that has the mandatory partition feature.

**Comment by drewbanin** [comment]
Thanks for making this issue @whittid4! I think that mandatory partition requirements are a good idea for source tables on BQ, so I'd be interested in figuring out a way to make this work.

The challenge here dbt tries to discern:
1. if there is a record within the acceptable freshness window
2. what the most recent datapoint for the table is

Adding a filter here won't necessarily impact dbt's ability to to determine if fresh records exist, but it probably _could_ impact dbt's knowledge of when the table was last loaded into.

I can imagine a `filter` config to the `freshness` block that looks like:

```yml
version: 2

sources:
  - name: ecommerce
    loaded_at_field: date

    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
      filter: "date > date_sub(current_date(), INTERVAL 7 days)     # this is new
      
    tables:
      - name: orders
```

You buy that?
