### ISSUE TITLE
[Wilt Chamberlain] Render `severity` config for tests

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1511]
### Feature description
As of 0.14.0, test severity can be configured with a syntax like:

```yml
version: 2

models:
  - name: my_models
    columns:
       - name: id
          tests:
            - unique:
                 severity: error
```

If possible, we should consider rendering the `severity` field with a macro context. This would make it possible to implement complex test logic in an environment-aware way. Eg: 
```yml
version: 2

models:
  - name: my_models
    columns:
       - name: id
          tests:
            - unique:
                 severity: "{{ 'error' if var('strict', false) else 'warn' }}"
```

Conceivably, users could put logic like this into macros, then use those macros in their severity specifications.

We've spoken about what ends up in the rendering context in #1255, so if this is mired in some larger conversation about the conversation context, then we can tackle this in a future release. If it's straightforward to implement now, I think it would be a great addition to the Wilt Chamberlain release of dbt.
