### ISSUE TITLE
Archive Function Schema

### ISSUE THREAD

**Issue by ddaltonrtr** [fishtown-analytics/dbt#1530]
### Issue description
When running the command `dbt archive`, the archive function doesn't take into consideration the target schema configured for the dbt project. 

### Results
For example, if you have a table called `analytics.orders` and run the model in dbt (`dbt run --model analytics_orders`), you can configure dbt to run it to the schema `analytics_dbt` (or something similar) for testing purposes (so you don't write over production data in your warehouse, etc).  However, when you run `dbt archive`, the function ignores all specifications for the dbt project and writes specifically to the schema specified in the dbt_project.yml file arguments (`target_schema`).  I would have thought that when running the command to archive the table locally, it would take into consideration the target schema configured for the project. 

### System information
The output of `dbt --version`: 
```
0.12.2
```

The operating system you're running on: Linux

The python version you're using (probably the output of `python --version`) 2.7.1

### Steps to reproduce
In the dbt_project.yml file, I have:
```
archive:
   - source_schema: analytics
   - target_schema: analytics
      tables:
         - source_table: orders
           target_table: orders_time_series
           updated_at: modified_at
           unique_key: order_id 
```
After running the command `dbt archive`, it will create the table `analytics.orders_time_series` instead of `analytics_dbt.orders_time_series`.  If I run the model locally, the table `analytics.orders` will write to the `analytics_dbt.orders`.
I believe the archive function does not take into consideration the `get_custom_schema.sql` macro (link to macro [here](https://github.com/fishtown-analytics/dbt/blob/111142ba4f8cdd3192b77fef103e2940cf43a4bf/dbt/include/global_project/macros/etc/get_custom_schema.sql).
