### ISSUE TITLE
Allow tables to be excluded from inherited freshness

### ISSUE THREAD

**Issue by tayloramurphy** [fishtown-analytics/dbt#1617]
### Feature description
It'd be nice to have an override option for tables to opt out of the freshness test. The specific use case is where there is a freshness test set at the source level and a specific table that needs to not be tested.

```
freshness: none
```

seems like it would be good. 

### Who will this benefit?
Data that is unlikely to change b/c it came from another system and it's kept for legacy/tracking purposes, but it's in the same schema as data that is being updated.

**Comment by drewbanin** [comment]
@tayloramurphy I don't recall if we explicitly designed for this or if it's a function of @beckjake just being a really good programmer, but this works currently!

You should be able to set `freshness: null` for a table, and dbt will exclude that table from source freshness calculations. It doesn't work with `none` because YAML interprets `none` as a string literal, whereas `null` becomes a proper Python `None` value. You can use any of the null keywords shown [in the yaml docs](https://yaml.org/type/null.html)

Let's leave this issue open to document this functionality (+ add a test?)

**Comment by beckjake** [comment]
There aren't any tests because this was just a happy accident! 😌 But it seems like a good behavior, I'm very into writing tests for this so we don't regress.

Maybe we should also document the fact that you can name multiple sources that all exist in the same schema - I suspect it's non-obvious and would have been my suggested workaround:

```

version: 2

sources:
  - name: pretty_fresh
    schema: source_schema
    freshness:
      warn_after:
        count: 8
        period: hours
    tables:
      - name: table_1
      - name: table_2
      - name: table_3
      # imagine having 20 of these!

  - name: not_fresh
    schema: source_schema
    freshness:
      warn_after:
        count: 7
        period: days
    tables:
      - name: table_21
      - name: table_22
      # but also having 20 of these in the same schema
```
