### ISSUE TITLE
Overly eager package version resolution 

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1631]
The following packages.yml spec fails:

```yml
packages:
  - package: fishtown-analytics/dbt_utils
    version: '>=0.1.23'
  - package: fishtown-analytics/audit_helper
    version: 0.0.1
```

`dbt-audit-helper` currently states deps on:

```yml
packages:
  - package: fishtown-analytics/dbt_utils
    version: [">=0.1.24", "<0.2.0"]
```

It appears that dbt over-eagerly resolves `>=0.1.23` to `0.2.1` (the current latest release of dbt-utils). This causes dbt to fail with an error indicating that the specified package list is non-resolvable. Instead, dbt should be able to resolve this series of package specs to one of `[=0.1.24,  =0.1.25]`.
