### ISSUE TITLE
Add a generate_database_name() macro

### ISSUE THREAD

**Issue by whisperstream** [fishtown-analytics/dbt#1695]
### Describe the feature
In the current version (v14.0), there exists a `{{ generate_schema_name_for_env }}` macro which works very well in dev mode, allowing a production run to write to the specified schema but writing all tables and views to a dev schema when in dev mode.  In the same way we need a `{{generate_database_name_for_env}}` macro for when a database is configured in the `dbt_project.yml` file.

Currently:
If I have in my `dbt_project.yml` file a section in `models` that reads:
```
models:
   product:
      database: mart_db
      materialized: view
      schema: mart_schema
```

and in my `profiles.yml` file I have:
```
my_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: *******

      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"

      role: "ur_{{ env_var('DBT_USER') }}"
      database: dbt_dev
```
Then my models in dev mode will be written using `mart_db` instead of `dev_db`.

### Describe alternatives you've considered
Right now to solve this I've created alternative `ref` macro called `xref` to override this behavior but it feels a bit clunky to do this and I will have to tell out dbt devs to all use `{{ xref('some table') }}` instead of the inbuilt `ref` function.

### Additional context
Not database specific, it's a dbt issue.

### Who will this benefit?
Anyone who wants to specify a set of **production** databases in their `dbt_project.yml` file in the same way that they might already do for their schemas using the existing `{{generate_database_name_for_env}}` macro but who also wants to have dbt write **all tables and views** into a single schema when in dev_mode.
