### ISSUE TITLE
Allow no-passphrase private keys

### ISSUE THREAD

**Issue by kmbenitez** [fishtown-analytics/dbt#1805]
### Describe the bug
The Snowflake connector (at least) requires a passphrase in the profile file to open a private key connection.

### Steps To Reproduce
Create a dbt target like the following:
```
    qa:
      type: snowflake
      account: my_account
      user: my_user
      role: ANALYST

      # Keypair config
      private_key_path: "path/to/my/no/passphrase/key"
      private_key_passphrase: None

      database: DB
      warehouse: WH
      schema: PUBLIC
      threads: 1
      client_session_keep_alive: False
```
Attempt to run against said DBT target. DBT will fail because no passphrase is provided. If, instead, a passphrase is provided, the connection will fail because the key is not encrypted.

### Expected behavior
Perhaps a warning in output that unencrypted keys are not the norm, requiring additional setting of override field in profile. If that's set, go ahead with the unencrypted key.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
0.14.2
```

**The operating system you're using:**
OSX
**The output of `python --version`:**
Python 3.7.3
