### ISSUE TITLE
`dbt docs generate` adding both source and model column names (source and model share name)

### ISSUE THREAD

**Issue by jkornblum** [fishtown-analytics/dbt#1883]
### Describe the bug
When running `dbt docs generate` and `dbt docs serve` the documentation shows the columns from both my source data and model data in the model documentation and in source documentation. I'm guessing this is because they share a name `case_info` and dbt doesn't know to keep them separate when building the catalog.

Snippet from `sources.yml`
```
    database: RAW_DEV
    tables:
      - name: area_info
        identifier: PSO_RESULT_AREA_INFO
      - name: case_info
        identifier: PSO_RESULT_CASE_INFO
```

I have a `models/pso_results/case_info.sql` file
```
{{
  config(
    alias="PSO_RESULT_CASE_INFO",
  )
}}

with clean_case_info as (
    select "//CaseID" as CASE_ID,
           "Name" as "NAME",
           "TaskID" as TASK_ID,
           ISO as ISO,
           "LoadDateTime" as LOADED_AT
from {{ source('pso_results', 'case_info') }}
)

select * from clean_case_info
```

when I serve docs I see this
![Screen Shot 2019-11-01 at 4 50 34 PM](https://user-images.githubusercontent.com/5368903/68058692-dbedd880-fcc7-11e9-8191-2e9e9719d268.png)

### Expected behavior
I expected `dbt docs` to understand and keep separate a source and a model regardless if the name matched.

### System information
**The output of `dbt --version`:**
```
installed version: 0.14.3
latest version: 0.14.3
```

**The operating system you're using:**
`Mac OSX 10.15`

**The output of `python --version`:**
```
Python 3.7.3
```
