### ISSUE TITLE
Testing expressions

### ISSUE THREAD

**Issue by philippe-lavoie** [fishtown-analytics/dbt#1896]
### Describe the feature
Please add an expression test. Example is 

```yaml
version: 2

models:
  - name: product
    tests:
      - expression: discount <= price
    columns:
      - name: id
        tests:
          - not_null
              
      - name: price
        tests:
          - expression: price > 0
              
      - name: discount
        tests:
          - expression: discount > 0
```

### Describe alternatives you've considered
I'd have to create a custom test file for each table instead of checking inside the schema file.

### Additional context
In Postgres, it's eascy to add a CHECK constraint (other DB too I believe, see https://www.postgresql.org/docs/7.4/ddl-constraints.html for examples). I'd like to implement those tests inside dbt too. 

### Who will this benefit?
Everyone since it will be easier to share more knowledge about constraints and validate the data more. 

Note: the expression needs to return a boolean and is basically just a valid SQL that fits in a single line.
