### ISSUE TITLE
Tests are not visible on the documentation for a model

### ISSUE THREAD

**Issue by philippe-lavoie** [fishtown-analytics/dbt#1915]
### Describe the feature
Add tests for both columns and models

### Describe alternatives you've considered
No alternative

### Additional context
I'm adding model level tests to capture more complex scenarios

```yaml
  tests:
  - dbt_utils.expression_is_true:
      expression: ((price > (0)::numeric))
  - dbt_utils.expression_is_true:
      expression: ((price > discounted_price))
  - dbt_utils.expression_is_true:
      expression: ((discounted_price > (0)::numeric))
```
I think it would be useful to see those in the documentation.

### Who will this benefit?
Everyone, more documentation the better.
