### ISSUE TITLE
Improve utility of database & schema information present in on-run-end hooks

### ISSUE THREAD

**Issue by dinedal** [fishtown-analytics/dbt#1924]
### Describe the bug
When running `dbt run` with a profile that includes the example macro of https://docs.getdbt.com/docs/on-run-end-context and writes to multiple databases, the grants are only executed on one of the databases, not the correct database of the schema

### Steps To Reproduce
Use the macro at https://docs.getdbt.com/docs/on-run-end-context

Use a `dbt_project.yml` similar to:
```
models:
  dbt_project:
    staging:
      schema: staging
      database: data_warehouse
    dim_models:
      schema: dim_models
      database: data_warehouse
    data_marts:
      schema: data_marts
      database: data_warehouse
    exports:
      schema: dropbox
      database: exports
on-run-end:
  - "{{ grant_on_schemas('all privileges', schemas, 'accountadmin', true) }}"
```

When any model in `exports` is run, confirm that the `grant` statement fails because it attempts to run on the database `data_warehouse` instead, where `dropbox` schema doesn't exist

### Expected behavior
The macro should execute on the database of the schema(s) passed in

### Screenshots and log output

```
12:09:17 | Concurrency: 16 threads (target='prod')
12:09:17 |
.
.
.
12:09:40 |
12:09:40 | Running 3 on-run-end hooks
12:09:40 | 1 of 3 START hook: dbt_project.on-run-end.0.............................. [RUN]
Database error while running on-run-end
Encountered an error:
Database Error
  002003 (02000): 01904edd-0042-9085-0000-243d012d02b2: SQL compilation error:
  Schema 'DATA_WAREHOUSE.DROPBOX' does not exist or not authorized.
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.14.3
   latest version: 0.14.4

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation
```

**The operating system you're using:**
OS X 10.14.5

**The output of `python --version`:**
Python 3.7.5

### Additional context
N/A
