### ISSUE TITLE
[LMA Regression] Reduce strictness of validation for Redshift IAM targets

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1925]
### Describe the bug
In previous releases of dbt, the `password` and `iam_duration_seconds` properties of Redshift targets using the `iam` method were optional. In 0.15.0-rc1, they are now required. This is a regression: both `iam_duration_seconds` and `password` should be optional properties when connecting to a Redshift cluster using an IAM role.

### Steps To Reproduce
Use a profile like:
```
redshift:
  target: iam
  outputs:
    iam:
      type: redshift
      method: iam
      cluster_id: my_cluster_id
      host: somedb.somehost.com
      user: drew
      port: 5439
      dbname: analytics
      schema: dbt_dbanin
      threads: 1
```

I can provide working creds to debug this in development.

One thing to note: Making the `password` field optional in the Redshift Connection does something funky behind the scenes - I see `TypeError: non-default argument 'port' follows default argument` from deep inside the dataclasses lib.
