### ISSUE TITLE
custom schema tests (via macros)

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#200]
create some mechanism to use a macro in a `schema.yml` file. Eg:

```sql
-- macros.sql

-- If a table contains any 👎   `{{expression}}s, then count(*) > 1 and the test fails!
{% macro all_thumbs_up(schema, table, expression) %}

select count(*) from {{schema}}.{{ table }}
where {{ expression }} != 👍 

{% endmacro %}
```

And in a `schema.yml` file:

```yml
events:
    constraints:
        all_thumbs_up:
            - my_table_name
```

We need to give this some more thought w/r/t how to handle macros with > 1 argument. Also, should macro-test names be namespaced somehow? Neat, powerful idea though
