### ISSUE TITLE
Unhelpful error message with malformed packages.yml

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/dbt#2017]
### Describe the bug
```
MacBook-Pro:analytics tristan$ cat packages.yml
packages:
  - package: fishtown-analytics/stripe
    revision: 0.3.1
```

I had recently switched from a git reference to this package to a hub reference, and forgot that I needed to change from `revision` to `version`. This is the error message I received, which made it significantly more challenging to debug:

```
MacBook-Pro:analytics tristan$ dbt clean && dbt deps
Running with dbt=0.15.0
Encountered an error while reading the project:
  ERROR: Runtime Error
  Invalid package config: at path []: 'local' is a required property
```

### Expected behavior
I would expect an error message like:
```
Required parameter version not supplied.
```
...or something similar.

**The output of `dbt --version`:**
```
MacBook-Pro:analytics tristan$ dbt --version
installed version: 0.15.0
   latest version: 0.15.0

Up to date!
```
