### ISSUE TITLE
Support Snowflake oauth authentication

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2050]
### Describe the feature
Support [oauth authentication](https://docs.snowflake.net/manuals/user-guide/python-connector-example.html#connecting-with-oauth) for Snowflake targets.

dbt's Snowflake plugin already supports the specification of an `authenticator` config. If the `authenticator` is configured as `oauth`, then dbt should also pass along a target config named `token` to the Snowflake connection constructor.

Note that a `password` is not required when using the `oauth` authenticator.

Example config:
```yml
my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: wxyz526
      # other standard snowflake configs here...
      
      # Specify oauth method + token
      authenticator: oauth
      token: abc123
```

### Who will this benefit?
Snowflake users that connect to the database using SAML providers.
