### ISSUE TITLE
Describe macro arguments in schema.yml files

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2081]
### Describe the feature
This PR https://github.com/fishtown-analytics/dbt/pull/2068 adds support for a `macros:` block in the `schema.yml` spec. We should update the `macros:` spec to support the specification of macro arguments + types, along with descriptions for those args.

Example:
```yml
macros:
 - name: my_macro
    arguments:
      - name: arg_1
        type: string
        description: The first argument
      - name: arg_2
        type: int
        description: "{{ doc('macro_arg2_docs') }}"
```

The `type`s here would be informational only and don't need be validated.

This might be kind of funky for macros that support varargs or kwargs, so i don't know that it's worthwhile to think about validating the arguments in this spec against the macro definition or anything. The use case here is to support effective documentation of these macros and, eventually, really cool editor integrations.

### Describe alternatives you've considered
I guess you could just pop all of this info into the macro description. Like a javadocs?
