### ISSUE TITLE
Improve error message for misconfigured models: block in dbt_project.yml

### ISSUE THREAD

**Issue by max-sixty** [fishtown-analytics/dbt#2122]
### Describe the bug
This is almost certainly user error rather than a bug. To the extent someone knows off-hand what I'm doing wrong that would be greatly appreciated. I'm new to using dbt with postgres and so have changed my setup somewhat.

### Steps To Reproduce
I posted the details on [SO](https://stackoverflow.com/questions/60178505/target-is-undefined-error-when-running-dbt), but not sure dbt is that active there, vs GH / Slack; I had to create the dbt tag.

Including here:

I have a `dbt_project.yml` like:

```yaml

name: rdb
profile: rdb
source-paths: ['models']
version: "0.1"

models:
  rdb:
    schema: cin
    materialized: table
    post-hook: 'grant select on {{ this }} to rer'
    on-run-end: 
        # TODO: fix
        - 'grant usage on schema "{{ target.schema }}" to rer'

```

DBT has worked really well. But with the `on-run-end` entry, it fails with `Compilation Error  'target' is undefined`. With that line commented out, it works fine.

Am I making a basic mistake? Thanks!

### System information
**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.15.1
   latest version: 0.15.2
```

**The operating system you're using:**
Linux

**The output of `python --version`:**
Python 3.6.8

**Comment by drewbanin** [comment]
hey @max-sixty - this is a pretty gross error message from dbt.

You'll just want to slide the `on-run-end` out of the `models:` config and make it a top-level configuration, eg:

```yml
on-run-end: "grant ..."

models:
  rdb:
    ...
```

I'll leave this issue open to track a feature request for a better error message for these kinds of things :)
