### ISSUE TITLE
'+' model selector with dbt test looks for incorrect models

### ISSUE THREAD

**Issue by jmace006** [fishtown-analytics/dbt#2132]
### Describe the bug

Using the '+' model selector with a tag for both run and test:

`$ dbt run -m +tag:external` and then  `$ dbt test -m +tag:external`

I get a number of missing model errors. The missing models were (correctly) not built by the run, so it seems like an issue they were expected by the test.

Digging around, it looks like `test` is trying to test models **not** included in the run DAG, but that have a `relationship:` test against a models that **are** included.

### Steps To Reproduce

1. Tag `model_a` with 'external'
2. Write a test against `model_b` checking a relationship against `model_a`
3. Remove any existing `model_b` relations in the db
3. Run `$ dbt run -m +tag:external`
4. Run `$ dbt test -m +tag:external` : expect an error for no `model_b`
5. Remove the relationship test for `model_b` against `model_a`
4. Run `$ dbt test -m +tag:external` : expect everything is happy again.
```
  - name: model_b
    columns:
    - name: model_b_id
      tests:
        - not_null
        - unique
    - name: model_a_id
      tests:
        - not_null
        - relationships: 
            to: ref('model_a') 
            field: model_a_id
```

### Expected behavior

Using the same model selectors would result in the same models in the DAG for both run and test. And if a model isn't built, its relationships to other models shouldn't be tested.

### Screenshots and log output

<img width="1005" alt="Screen Shot 2020-02-13 at 9 00 03 am" src="https://user-images.githubusercontent.com/31755315/74385478-61dcfc00-4e3f-11ea-85cb-1fc658ac257f.png">

<img width="1005" alt="Screen Shot 2020-02-13 at 9 00 24 am" src="https://user-images.githubusercontent.com/31755315/74385530-791be980-4e3f-11ea-88d0-043403f14150.png">

<img width="1019" alt="Screen Shot 2020-02-13 at 8 58 53 am" src="https://user-images.githubusercontent.com/31755315/74385471-5d184800-4e3f-11ea-833f-0c272568f8fc.png">

### System information
**Which database are you using dbt with?**

postgres

**The output of `dbt --version`:**
```
installed version: 0.15.0
latest version: 0.15.2
```

**The operating system you're using:**

macOS Mojave (10.14.6)

**The output of `python --version`:**

Python 3.7.3

### Additional context

This went unnoticed until I cleared out all old models before the run & test, since finding old copies of the models from a full run would satisfy the tests.
