### ISSUE TITLE
dbt seed mishandles leading zeros in string columns

### ISSUE THREAD

**Issue by skritch** [fishtown-analytics/dbt#2165]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

DBT strips leading zeros from string columns unless there is a non-purely-numeric value elsewhere in the column.

I'm pretty sure this is due to Agate and may be handled by the other recently-closed issues pertaining to that library. Perhaps this can turn into a test case in that case.

### Steps To Reproduce

Testing with DBT 15.0 vs Redshift.

Create a csv called `bug_report.csv` in your seeds directory:
```
one_numeric_string_col,one_numeric_string_col_quoted,nonempty_string_col,two_numeric_strings_col,inferred_col,inferred_quoted_col,inferred_two_quoted_col
000,"000",000,000,000,"000","000"
,,other_string,100,,"100"
,,,,,,
```
and add a configuration to `dbt_project.yml`:
```
seeds:
  your_project_name:
    bug_report:
      column_types:
        one_numeric_string_col: varchar(36)
        one_numeric_string_col_quoted: varchar(36)
        nonempty_string_col: varchar(36)
        two_numeric_strings_col: varchar(36)
```

Run `dbt seed`.

Run `select * from <your target schema>.bug_report`, and you get:
```
0,0,000,0,0,0,0
,,other_string,100,,100,
,,,,,,

```
![image](https://user-images.githubusercontent.com/2220562/75469221-a34fca00-595c-11ea-8863-64180fdde7df.png)

Most of the values in the first row have been truncated to a single `0`. 

### Expected behavior

String columns preserve leading 0s in their values.

Possibly, a column consisting ONLY numeric values with a leading zeros are inferred as a string column.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.15.0
latest version: 0.15.2

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

```

**The operating system you're using:**

**The output of `python --version`:**
