### ISSUE TITLE
Advanced node selection syntax

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt#2172]
We want to enable a mechanism of node selection that is:

- More powerful, composable, extensible
- In a structured data format
- Possible to check into version control

We think that this is best implemented as YML. It should be similar to CLI `--models` and `--select` syntaxes, but it will also allow us to move beyond what's possible with CLI flags + arguments.

### Selectors

- resource name
- resource type
- model materialization type
- tags
- project/package
- subdirectory
    - file path literals
- Node dependencies. We can make these more verbose in YML than the current selectors on the CLI:
    - parents: `+my_model`
    - children: `my_model+`
    - children and all their parents: `@my_model`
    - *proposed:* models that depend on macros (and their children?): `my_macro+`

### Set logic

- unions (inclusive OR): current default behavior
- exclusion: possible on the CLI with `--exclude`
- intersections (AND): not yet possible, proposed in #2167
- exclusive OR will be possible as the combination of the three above (`union(A,B) —exclude intersect(A,B)`)

### Well defined "pseudo-selectors"

We can encode a dynamic selector that returns resources based on a set of conditions, which dbt uses to pick specific nodes at build time. I'm including a couple possibilities of varying complexity, mainly to spur the imagination:

- `this_package_only`
    - Only execute models + tests that are defined in the current "home? project
    - Dynamic based on the project directory from which it's run.
- `build_if_missing`
    - Exclude model nodes that already exist as relations in the `target` database + schema
- `build_if_changed`
    - point to  `manifest.json` from a different dbt build, and dbt can compare to infer changed resources
    - sensible pattern: select all nodes with changes + their children
- `build_if_updated`
    - point to a `manifest.json` from a different dbt build, _and_ the result of a more recent `dbt source snapshot-freshness`. dbt can determine whether 

### (Very) hypothetical spec

```yml
version: 2

selectors:

  - name: snowplow_marketing_nightly    # human-friendly name for this custom node grouping
    definition:
      - union:          # include nodes for which ANY of the selectors below is true
        - intersect:    # include nodes for which ALL of the selectors below are true
          - tag: nightly
          - tag: marketing
          - package: snowplow
          - materialized: incremental
        - union:
          - resource_name: snowplow_marketing_custom_events
          - file_path: "models/snowplow/marketing/custom_events.sql"
          - model_dir: "snowplow/marketing"
        - intersect:
          - resource_type: seed
          - package: snowplow
          - exclude:
              resource_name: country_codes
  
  - name: ci    # a different custom node grouping
    definition:
      - dynamic: build_if_changed
        parents: false
        children: true
```

```
dbt run --selector snowplow_marketing_nightly
```
```
dbt run --selector ci
dbt test --selector ci
```

### Prior art

This carries on the legacy of several past issues (going back to #550, if not earlier). It's something we've been thinking about for some time.

Looking ahead, I believe that a good approach here will form the basis for features we're very interested in supporting:
- complex workflows
- smarter CI
- dev/prod environments in larger/multi-package projects
