### ISSUE TITLE
Threshold argument for Test Severity

### ISSUE THREAD

**Issue by sanjanasen96** [fishtown-analytics/dbt#2219]
### Describe the feature
- A `threshold` argument for `test severity`. 
- Useful for more flexibility around test severity. Eg: If the test fails for < 10 IDs, severity can be set to a warning. If the test fails for > 10 IDs, severity can be set to an error.

### Describe alternatives you've considered
- Currently we've been keeping an eye on daily test failures and switching severity around for tests as needed. This is not scalable or efficient. 

### Additional context
- This is not database specific. 

### Who will this benefit?
- We've found multiple use cases in relationship tests in multi-layer modeling like event modeling.

**Comment by jtcohen6** [comment]
Worth saying off the bat:
* Everything discussed in this issue and the comment below can be done today with custom schema tests that override the builtin `unique`, `not_null`, etc
* It would _also_ be really cool if the builtin tests included some sane functionality that points in this direction

I think becomes all the more relevant as we start to work with bigger datasets. We already run into issues with tiny failures for `relationships` tests because tables are loaded asynchronously, but it's also important for handling cases where, e.g., a billion-row table has 10 duplicate records.

One complication I'd throw out is **absolute** vs. **relative** thresholds. I may want a test to error if the number of failures is >1% of the overall row count, instead of being greater than an arbitrary number.

While not directly related, I also see this working in combination with a `where` (subset/partition) argument. E.g. I only want to test data from yesterday + today, and I want it to warn or error if there are <=1% or >1% nulls, respectively. Maybe that looks like:
```yml
models:
  - name: my_big_model
    columns:
      - name: important_column
        tests:
          - not_null:
              warn_after: {count: 0, percent: true}
              error_after: {count: 1, percent: true}
              where: "date_day >= (current_date() - interval 1 day)"
```

**Comment by drewbanin** [comment]
Check out #1173 - I think we could make a change like this in the scope of that issue (or shortly thereafter).

- I like the idea of the `where` predicate here -- TBD if that's built-in to dbt, or if we require schema test authors to support it in their test definitions though. I do imagine we could filter the referenced model in a subquery when interpolating the table reference, for example :)
- I imagine we could calculate percentages pretty easily if we also run a `count(*)` on the specified model
- I like `warn_after` and `error_after` more than I like `severity: true` -- it seems a lot more flexible!

**Comment by sean-rose** [comment]
I'm also very much in favor of supporting relative thresholds, but for the syntax instead of `{count: <number>, percent: true}` I'd suggest just having a number followed by a `%`, and if there is no `%` treat it as a row count.

```yaml
- not_null:
    error_after: 10  # Row count

- not_null:
    error_after: 10%  # Relative percentage
```
