### ISSUE TITLE
 Sources should have access to variables defined in dbt_project.yml

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/dbt#2269]
### Describe the feature
`var` functions in a source definition should have access to `vars` defined in a `dbt_project.yml` file.

```yml
# dbt_project.yml

models:
  vars:
    segment_schema: my_segment_schema
```

```yml
models/segment.yml

version: 2

sources:
  - name: segment
     schema: "{{ var('segment_schema') }}`
```

### Describe alternatives you've considered
This currently works with CLI vars.

We've also considered nesting this under `sources:` in the `dbt_project.yml`
```yml
# dbt_project.yml

sources:
  vars:
    segment_schema: my_segment_schema
```

### Additional context
[Related Loom video](https://www.loom.com/share/174ad815978047ec81c7144d00e04365)

### Who will this benefit?
Package authors
