### ISSUE TITLE
dbt slack integration

### ISSUE THREAD

**Issue by Javier162380** [fishtown-analytics/dbt#2271]
### Describe the feature

Hi, I have been working with DBT for two years since now and it is great. 

We have implemented some kind of features with the DBT API for our company and I think it could be great if we can implement it in the DBT core package.
 
One of the main features is the ability to notify in a chat system all the different DBT transactions are taking place. So the analytics team has an overview of what the different team members are doing or how periodically triggers are affecting the data model.

As an example, we run a test battery over our DWH daily and the output is notified to a slack channel.

### Describe alternatives you've considered
It would be awesome if in the profiles we can add a configuration of a notification channel, and have an extra argument to choose if a DBT command should notify or not the out to a channel, depending on if success or if fails.

I will start giving a slack support as is a pretty simple API and auth, but dessinging in a way other chats can be supported. I image a profiles.yml configuration as 
```yaml
my_profile:
  target: "{{ env_var('TARGET') }}"
  outputs:

      dev:
        type: redshift
        threads: 1
        host: "{{ env_var('REDSHIFT_URL') }}"
        port: 5439
        user: "{{ env_var('REDSHIFT_USERNAME') }}"
        pass: "{{ env_var('REDSHIFT_PASSWORD') }}"
        dbname:  "{{ env_var('REDSHIFT_DBNAME') }}"
        schema: "{{ env_var('REDSHIFT_SCHEMA') }}"
      prod:
        type: redshift
        threads: 1
        host: "{{ env_var('REDSHIFT_URL') }}"
        port: 5439
        user: "{{ env_var('REDSHIFT_USERNAME') }}"
        pass: "{{ env_var('REDSHIFT_PASSWORD') }}"
        dbname: "{{ env_var('REDSHIFT_DBNAME') }}"
        schema: dbt_prod
        notification_system:
              type: slack
              weebhook_url: "{{ env_var('SLACK_WEEBHOOK_URL') }}"
              notify_on:
                     - all|on_failure|on_success(i imagine here a trigger rule similar to airflow)
```
The idea is to be a able to generate a message interface generic for all the different operations.

### Additional context
Is this feature database-specific? Which database(s) is/are relevant? Please include any other relevant context here.

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.
