### ISSUE TITLE
Override and disable sources in packages

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2283]
### Describe the feature
If a source is located in a package, there is currently no way to disable that source to remove it from the manifest or the compilation context. To this end, sources should support an `enabled` config, as well as a first-class entry in the `dbt_project.yml` file.

Example syntax:
```
# models/airflow/sources.yml

sources:
  - name: snowplow
    enabled: false
    tables: [ ... ]
```

Source configurations (database, schema, enabled, freshness, etc) should be configurable via a `sources:` block in the `dbt_project.yml` file:

```
sources:
  my_source: # configure sources in the my_source package
    airflow: # configure sources in the airflow/ directory
      snowplow: # configure the snowplow source
        database: ....
        schema: ....
        enabled: true
        tables:
          event: # configure the snowplow.event source table
            loaded_at_field: collector_tstamp
```

Implementation notes:
 - The configs applied in a `schema.yml` file have historically been totally separate from configs applied in the `dbt_project.yml`. It would be a good thing to start bringing those two together, but for the scope of this issue, no sweeping changes are _required_ for model configs.
 - The example above includes a hierarchical config based on file path. This would be consistent with how we handle configs for models (a good thing), but it is a tiny bit wonky (paths for .yml files are not incredibly well defined at the moment)
 - Source config precedence is similar to model config precedence
    1. in-package dbt_project.yml file
    2. in-package schema.yml file
    3. root-project dbt_project.yml file
    4. root-project schema.yml file
 - If a source is disabled, then `source()` calls referencing that source should fail and the source should not be represented in the manifest (akin to disabled models)
