### ISSUE TITLE
Regression: dbt does not allow integer dataset names on BigQuery

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2384]
### Describe the bug
BigQuery allows stringy dataset names that contain only digits, but dbt fails at startup if such a dataset name is provided. Is this a function of dbt's new NativeEnvironment rendering for jinja?

### Steps To Reproduce
Use a profile like:
```
    dev:
      type: bigquery
      method: service-account
      project: '...'
      dataset: "1991"    # This is the important part
      threads: 1
      keyfile: ...
      location: US
      timeout_seconds: 1
      retries: 3
```

A `dbt run` will fail indicating that the provided profile is invalid:
```
Credentials in profile "bq", target "dev" invalid: 1991 is not of type 'string'
```

### Expected behavior
dbt should create models in a dataset named `1991`

### dbt version
```
dev/octavius-catto
```
