### ISSUE TITLE
'NoneType' object has no attribute 'get' on non-empty profiles.yml

### ISSUE THREAD

**Issue by mohnish7** [fishtown-analytics/dbt#2447]
On running 
`dbt run` 
I get the following error

```
Running with dbt=0.16.1
Encountered an error:
'NoneType' object has no attribute 'get'
```

Issue #555 stated that this happens when profiles is empty, but that isn't the case here. I'm following [this guide](https://dataschool.com/sql-optimization/start-modeling-data/)

I'm using bigquery, dbt 0.16.1, and python 3.7.7 on OS Catalina 10.15.2

**Comment by beckjake** [comment]
That guide is wrong, its example is missing important whitespace. The example profiles.yml should actually look like this:
```
my-bigquery-db:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: happy-vegetable-211094
      dataset: soCleaned
      threads: 1
      keyfile: /users/matt/BigQuerykeyfile.json
      timeout_seconds: 300
```
