### ISSUE TITLE
vars defined at the global level in dbt_project.yml v2 don't end up in schema parsing

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#2472]
### Steps to reproduce
(copy+pasted from Claire in slack)

Add a variable to a package, e.g.:
```
name: 'marketo_source'
version: '1.0.0'
require-dbt-version: '>=0.17.0'
config-version: 2
vars:
    schema: marketo
    database: raw
```

2. Call the var in the same package:
```
version: 2
sources:
  - name: marketo
    schema: "{{ var('schema') }}"
    database: "{{ var('database') }}"
    tables:
      - name: lead
```

3. Install the package in another project, and dbt compile

4. Get this error:
```
Compilation Error
  Required var 'database' not found in config:
  Vars supplied to <Configuration> = {}
```

5. Move the vars to be package scoped:
```
name: 'marketo_source'
version: '1.0.0'
require-dbt-version: '>=0.17.0'
config-version: 2
vars:
  marketo_source:
    schema: marketo
    database: raw
```

6. Try again, everything works.

### Expected behavior:
The var should be resolved in both instances. Vars available in the global scope should behave as if they were in package scope unless overridden by package scope.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
dbt 0.17.0rc1
```

Any OS, any Python, any database
