### ISSUE TITLE
DELETE statement isn't committed within on-run-end hook.

### ISSUE THREAD

**Issue by dlmiddlecote** [fishtown-analytics/dbt#2495]
### Describe the bug

I have added an `on-run-end` hook to my project, that has a single statement: `DELETE FROM ...` to do some cleanup. However, when I `dbt run`, the data is not cleaned up. If I add `; commit;` to the end of the statement, i.e. `DELETE FROM ...; commit;`, and `dbt run` again, the data is deleted.

### Steps To Reproduce

The behaviour I'm trying to account for is like so:

```
                   ┌ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┐
┌──────────────┐     ┌──────────────┐       ┌──────────────┐
│              │   │ │              │       │              │ │
│    STREAM    │────▶│    BATCH     │──────▶│    TABLES    │
│              │   │ │              │       │              │ │
└──────────────┘     └──────────────┘       └──────────────┘
                   │                                         │
                     ┌─────────────────────────────────────┐
                   │ │                                     │ │
                     │    DBT                              │
                   │ │                                     │ │
                     └─────────────────────────────────────┘
                   └ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┘
```

I have a stream with contains new raw json blobs. With `on-run-start`, I run `INSERT INTO BATCH SELECT RAW FROM STREAM`.

`BATCH` is then a `source` for dbt, and transforms are made to turn it into some tables.

At the end, `on-run-end`, I then want to clean up the BATCH table, running `DELETE FROM BATCH`. This does not commit, however, and I'm left with data in BATCH at the end of a run.

In terms of configuration this looks like:
- `dbt_project.yml`
```yml
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "test"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "dev"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
# models:
#     test:
#         # Applies to all files under models/example/
#         example:
#             materialized: view

on-run-start:
    - INSERT INTO BATCH (RAW, TIMESTAMP) SELECT RAW, TIMESTAMP FROM STREAM;

on-run-end:
    - DELETE FROM BATCH [; COMMIT;]
```

- `schema.yml`
```yml
version: 2

sources:
  - name: test
    schema: TEST
    tables:
      - name: BATCH
```

- `models/test.sql`
```sql
{{ config(materialized='table') }}

WITH BATCH_LATEST AS (
  SELECT
    CAST(RAW:object_id AS BIGINT)                   AS OBJECT_ID,
    CAST(RAW:version AS INTEGER)                    AS VERSION,
    CAST(RAW:timestamp AS TIMESTAMP WITH TIME ZONE) AS EMITTED_TIMESTAMP,
    RAW,
    ROW_NUMBER() OVER (PARTITION BY RAW:object_id ORDER BY RAW:version DESC) AS RNK
  FROM {{ source('test', 'BATCH') }}
)
SELECT
  ACCOUNT_ID,
  OBJECT_ID,
  VERSION,
  EMITTED_TIMESTAMP,
  RAW
FROM BATCH_LATEST
WHERE RNK = 1
```

### Expected behavior

I'd expect the data to be deleted without having to `commit` manually.

### Screenshots and log output
Debug log output without `; commit;`:
```
2020-05-28 00:02:02.038969 (MainThread): Using snowflake connection "master".
2020-05-28 00:02:02.039269 (MainThread): On master: /* {"app": "dbt", "dbt_version": "0.17.0b1", "profile_name": "cdp", "target_name": "test", "connection_name": "master"} */
DELETE FROM <...>;
2020-05-28 00:02:02.910266 (MainThread): SQL status: SUCCESS 5 in 0.87 seconds
```

Debug log output with `; commit;`:
```
2020-05-28 00:04:17.663912 (MainThread): Using snowflake connection "master".
2020-05-28 00:04:17.664125 (MainThread): On master: /* {"app": "dbt", "dbt_version": "0.17.0b1", "profile_name": "cdp", "target_name": "test", "connection_name": "master"} */
DELETE FROM <...>;
2020-05-28 00:04:18.553232 (MainThread): SQL status: SUCCESS 5 in 0.89 seconds
2020-05-28 00:04:18.553514 (MainThread): Using snowflake connection "master".
2020-05-28 00:04:18.553689 (MainThread): On master: commit;
2020-05-28 00:04:18.884134 (MainThread): SQL status: SUCCESS 1 in 0.33 seconds
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
0.17.0-b1
```

(This was also the case in 0.16.1).

**The operating system you're using:** Mac OS

**The output of `python --version`:** Python 3.8.1

### Additional context

This is my first time using dbt, so I could well be doing something incorrectly...

As a side note, my table 'TEST' (from test.sql) also doesn't have any data in it, but when I run the command outputted by the debug logs (i.e. `create or replace table ...`) it does work. Maybe there's a 'commit' issue else where, or something I'm doing wrong...
