### ISSUE TITLE
Better error handling for compilation exceptions in .yml files

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2499]
### Describe the bug
A malformed yml file can result in an error like:
<img width="399" alt="Screen Shot 2020-05-29 at 9 15 37 AM" src="https://user-images.githubusercontent.com/1541139/83263674-fa984d00-a18c-11ea-8c52-4148325edaa7.png">

Instead, this error should include information about the file in which the errant jinja code was found.

### Steps To Reproduce
Create a .yml file with the contents:
```
version: 2

models:
  - name: debug
    meta:
      abc: 123

      columns:
        - name: id
          description: '{{ doc("mydoc") }}'
```

Note that the columns entry is errantly indented under `meta`.

Run `dbt ls` or `dbt compile` to see the compilation exception.

### Expected behavior
I would expect to see the filename containing the errant code in the raised exception.

**The output of `dbt --version`:**
```
v0.17.0-rc3
```
