### ISSUE TITLE
Extend vars support in run-operations to follow same conventions as standard dbt run

### ISSUE THREAD

**Issue by mdesmet** [fishtown-analytics/dbt#2532]
### Describe the feature
The run-operation feature also supports vars, however they can only provided through CLI, this seems a bit cumbersome. Why can't it follow the same logic as within a dbt run as stated in https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-variables/#variable-precedence. This will provide the user to specify the vars in the yaml file just as usual instead of having to provide it in dict format through the CLI.

Imagine having to pass these kind of structures through CLI:
```
vars:
    var1: whatevervar
    var2:
      - name: name1
        list:
        -  entry1
```

### Describe alternatives you've considered
We can use db run instead, however we would like to use run-operation to enable all things related to CI/CD and this is not necessary during development.

### Additional context
Any/All dbs

### Who will this benefit?
Users want simpler automation, build and CI scripts

**Comment by drewbanin** [comment]
hey @mdesmet - I don't think I understand the question you're asking here -- dbt currently supports referencing variables from the `dbt_project.yml` file! Here's an example that I just tested with dbt v0.17.0:

```
# dbt_project.yml
name: test_project
version: 1.0.0

config-version: 2

vars:
  var1: abc
  var2: def
...

```
-- macros/test_op.sql

{% macro test_op_vars() %}

    {% do log("var1=" ~ var('var1'), info=true) %}
    {% do log("var2=" ~ var('var2'), info=true) %}

{% endmacro %}
```

Run with:
```
$ dbt run-operation test_op_vars
var1=abc
var2=def
```

**Comment by mdesmet** [comment]
I got it to work with 0.17.0. I was still on 0.16.1, I was confused by the section on https://docs.getdbt.com/docs/building-a-dbt-project/using-operations#context that mentions that vars are limited to the CLI passed parameters.

Not sure if It also should work on 0.16.1?

Anyway this can be closed as it is already working. :)

**Comment by drewbanin** [comment]
oh - that makes sense! For reference (and for anyone else that stumbles upon this issue): vars in dbt < 0.17.0 could be scoped to particular packages or paths.

This would not work for example:
```
# dbt_project.yml

# using dbt v0.16.1

models:
  my_package:
    some_path:
      vars:
        abc: 123
        def: 456
```

Here, the vars `abc` and `def` are scope to the `models/some_path` path in the `my_package` package. This means that a macro called via a run-operation would not have these variables in-scope.

dbt v0.17.0 removes the concept of path-scoped variables, so this problem kind of goes away!

Thanks for opening this issue - it was a good question. Glad to hear it's working in 0.17.0!
