### ISSUE TITLE
BigQuery Service Account JSON Authentication not working

### ISSUE THREAD

**Issue by darwinyip** [fishtown-analytics/dbt#2553]
### Describe the bug
Trying to authenticate to BigQuery using [Service Account JSON Authentication](https://docs.getdbt.com/docs/supported-databases/profile-bigquery/#service-account-json-authentication) because I'm running dbt from a docker container. Since storing the creds inside the container is not safe, I am passing each field as environment variable and parsing them in `profiles.yml`.

### Steps To Reproduce
In `profiles.yml`:

```
      keyfile_json:
        type: "{{ env_var('BIGQUERY_TYPE') }}"
        project_id: "{{ env_var('BIGQUERY_PROJECT_ID') }}"
        private_key_id: "{{ env_var('BIGQUERY_PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('BIGQUERY_PRIVATE_KEY') }}"
        client_email: "{{ env_var('BIGQUERY_CLIENT_EMAIL') }}"
        client_id: "{{ env_var('BIGQUERY_CLIENT_ID') }}"
        auth_uri: "{{ env_var('BIGQUERY_AUTH_URI') }}"
        token_uri: "{{ env_var('BIGQUERY_TOKEN_URI') }}"
        auth_provider_x509_cert_url: "{{ env_var('BIGQUERY_AUTH_PROVIDER_X509_CERT_URL') }}"
        client_x509_cert_url: "{{ env_var('BIGQUERY_CLIENT_X509_CERT_URL') }}"
```

However when trying to run anything I get:
```
Please log into GCP to continue
Encountered an error:
Got a non-zero returncode running: ['gcloud', 'auth', 'application-default', 'login']
```

### Expected behavior
dbt should run normally

### System information
**Which database are you using dbt with?**
bigquery

**The output of `dbt --version`:**
```
# dbt --version
installed version: 0.16.0
   latest version: 0.17.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

```

**The operating system you're using:** python:3.7.4-slim

**The output of `python --version`:** 3.7.4

### Additional context
```
# gcloud --version
Google Cloud SDK 297.0.0
alpha 2020.06.12
beta 2020.06.12
bq 2.0.58
core 2020.06.12
gsutil 4.51
kubectl 2020.06.12
```
