### ISSUE TITLE
configured hooks are eagerly rendered when prefixed with a `+`

### ISSUE THREAD

**Issue by beckjake** [fishtown-analytics/dbt#2583]
### Describe the bug
When using config-version 2, users can prefix a config item with a `+` to make sure it isn't treated as a part of the "config hierarchy". While it's only important for dictionaries, it's accepted for any key inside a resource configuration block (`models`, `seeds`, etc). However, prefixing `pre-hook` or `post-hook` to make them `+pre-hook: ...` or `+post-hook: ...` caused them to be rendered during config parsing, instead of being deferred to runtime. 

### Steps To Reproduce
In `dbt_project.yml`:
```yml
name: test
version: '1.0'
config-version: 2
models:
  test:
    +post-hook:
      - grant select on {{ this }} to some_user
```

Your post-hooks will run without the `this`.

### Expected behavior
`+post-hook` should behave exactly like `post-hook`.

Note that I don't necessarily expect top-level fields like `on-run-start` to support the `+` prefix.

### System information
Any database, any python, `dbt==0.17.0`
