### ISSUE TITLE
Empty string in `accepted_values` fails the test

### ISSUE THREAD

**Issue by chrisluedtke** [fishtown-analytics/dbt#2587]
### Describe the bug
When using an empty sting, `''`, in an `accepted_values: values` list, the compiled SQL checks for `'None'`, which fails the test if the data actually contain an empty string.

### Steps To Reproduce
```yml
      - name: col_name
        tests:
          - accepted_values:
              values: ['']
```
```sql
with all_values as (

    select distinct
        col_name as value_field

    from database.schema.table

),

validation_errors as (

    select
        value_field

    from all_values
    where value_field not in (
        'None'
    )
)

select count(*) as validation_errors
from validation_errors
```

### Expected behavior
Test for and accept a `''` accepted value.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.17.0
   latest version: 0.17.0

Up to date!

Plugins:
  - postgres: 0.17.0
  - snowflake: 0.17.0
  - bigquery: 0.17.0
  - redshift: 0.17.0
```

**The operating system you're using:**
`Ubuntu 20.04 LTS`

**The output of `python --version`:**
`Python 3.8.1`

### Additional context
We noticed after upgrading from dbt 0.15 to 0.17.

**Comment by jtcohen6** [comment]
@chrisluedtke We changed the way that data types are rendered between YML/Jinja in 0.17.0. Could you try changing your test definition to one of:
```yml
      - name: col_name
        tests:
          - accepted_values:
              values: ["''"]
```
Or:
```yml
      - name: col_name
        tests:
          - accepted_values:
              values: ["{{ '' | as_text }}"]
```
And see if that works?

I realize both double-quoting and adding the filter feel a bit awkward. We're thinking about what a better longer-term solution would look like (see https://github.com/fishtown-analytics/dbt/issues/2531).
