### ISSUE TITLE
yaml quoting not working with NativeEnvironment jinja evaluator

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2597]
### Describe the bug
dbt's NativeEnvironment introduced a functional change to how Jinja strings are evaluated. In dbt v0.17.0, a schema test can no longer be configured with a quoted column name.

### Steps To Reproduce
```
# schema.yml

version: 2
models:
  - name: debug

    columns:
      - name: MyId
        quote: true
        tests:
          - relationships:
              to: ref('debug')
              field: '"MyId"'
```

```
-- models/debug.sql

select 1 as "MyId"
```

**Results:**
```
Database Error in test relationships_debug__MyId____MyId___ref_debug_ (models/schema.yml)
  column "myid" does not exist
  LINE 12:     select MyId as id from "analytics"."test_schema"."debug"
                      ^
  HINT:  Perhaps you meant to reference the column "debug.MyId" or the column "child.id".
  compiled SQL at target/compiled/neondwh/models/schema.yml/schema_test/relationships_debug__MyId____MyId___ref_debug_.sql
```

### Expected behavior
I would expect the yaml/jinja string `'"MyId"'` to be resolved to the string `"MyId"`, not `MyId`.

**The output of `dbt --version`:**
```
dbt v0.17.0
```

**The operating system you're using:** macOS

**The output of `python --version`:** 3.7.7

### Additional context
Using `Jinja2==2.11.2`

**Comment by beckjake** [comment]
Is this a dupe of https://github.com/fishtown-analytics/dbt/issues/2468 ?

**Comment by drewbanin** [comment]
I don't think so -- the issue here is that strings like `'"my string"'` are being stripped of quotes, right?

**Comment by jtcohen6** [comment]
As I understand it, a resolution to #2468 could offer a resolution here too, if `debug.MyId` were configured with `quote: true`.  But the more straightforward issue is around the ability to pass quotes as part of a string value through the native env, which I think more closely relates to #2531.

Cringe-y, but this does work:
```yml
- relationships:
    to: ref('my_first_dbt_model')
    field: '''"MyId"'''
```
