### ISSUE TITLE
Seed descriptions are not persisted on BigQuery

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2598]
### Describe the bug
When `persist_docs` is configured to persist descriptions for BigQuery relations, the resulting seed tables in BigQuery are not build with relation-level descriptions.

### Steps To Reproduce
```
# dbt_project.yml
config-version: 2
seeds:
    +persist_docs:
      relation: true
      columns: true
```

```
# models/schema.yml
version: 2
seeds:
  - name: my_seed
    description: my seed
    columns:
      - name: the_column
        description: column description
```

```
$ dbt seed
```

The resulting relation is not configured with a description in BigQuery.

### Expected behavior
I expect to see a configured description in BigQuery for the seed table.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
dbt v0.17.1-rc2
```
