### ISSUE TITLE
Slim CI runs, via state comparison and deferred refs

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt#2641]
## Slim CI: MVP

For 0.18.0, we want to prioritize making the following use case possible:
```
dbt run -m state:modified+ --defer --state prod-target/
```

What does this do?
1. `--state prod-target/`: Compare the current project against the manifest specified in the `--state` arg (#2465)
2. `state:modified+`: Select the set of model nodes that are not present in the state manifest, or differ from the same-named model nodes in state manifest, and their children
3. `--defer`: Compile any `ref()` in a selected model that points to a node _not_ in the selection group by using the state manifest, instead of the default (target-informed) namespace (#2527)
4. Run all selected models

In terms of the user-side setup required for the V1 of this, we expect:

1. **dbt Cloud** will have a behind-the-scenes mechanism to accept user input (`job_id`) and surface up-to-date artifacts, either:
    - to a relative path that is predictable, stable, and git-ignored (e.g. `.dbt-cloud/`)
    - to an absolute path that is encoded in an env var
2. In **Airflow/CircleCI/etc**, in the steps before running dbt, users write bash commands to grab the artifact files from wherever they are and copy them to wherever they need to be

The underlying constructs open a pandora's box of questions that we'll need to continue thinking through:
* Deferring `ref`s in ephemeral models? Is this a performance killer during compilation?
* How do we reflect "deferral" in dbt artifacts? The run results should reflect that the model selected from the "deferred" namespace. What should the manifest do?
* What about models that should never/always be deferred? We want to be wary of global flags to control behavior which users really want to control on a per-model basis (see: `--full-refresh`).
* Are there cases where someone wants to compare state against one manifest and defer references to a different one?
* Should dbt offer handy mechanisms to move artifacts around?

There's more thinking to do. We're not going to block a first version of this by worrying about all the cascading implications.

## Related art

As a selector (#2640):

```yml
selectors:
  - name: delta_plus
     definition:
       method: state   # this would return an error if `--state` is not passed
       value: modified
       children: true
```

As a workflow (#1842):

```yml
workflows:
  - name: slim_ci
    steps:
      # assuming the prod manifest is already in a folder called `prod-target`
      - name: run_changed
        description: Run changed models, parents, children
        command:
          subcommand: run
          selector: delta_plus
          defer: true
          state: 'prod-target'
      - name: good_tests
        description: Run my good tests
        command:
          subcommand: test
          selector: delta_plus
          on_error: continue
      - name: generate_docs
        description: Make my docs
        command:
          subcommand: docs generate
```

This is effectively a Makefile, with a few added benefits:
* Define dbt subcommands as dicts instead of CLI arg syntax
* Control `on_error` behavior: continue to next workflow step, or stop the workflow altogether

I feel good about adding this functionality, and the syntax above feels reasonable. The big unknowns are (a) how people will use these, and (b) how dbt Cloud could compellingly hook into these. If possible, I'd like to add _very_ initial support for workflows in 0.18.0 and leave it undocumented / call it out as liable to change.
