### ISSUE TITLE
New node type: reports

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt#2730]
**Edit: I previously called these `exposures`. I've changed it to `report` to keep it more tangible for this first version.

dbt Core needs to have a semantic understanding of a `report`. A "report" is a generalization of a "dashboard", though it could also be an ML model, Jupyter notebook, R Shiny app, in-app data viz, etc.

The `report` node serves two purposes:
1. Define a set of models as dependencies
2. Define metadata to populate an embed tile and special dbt-docs "landing page"

### Why?

* We want to be able to push information about data quality and lineage from dbt into external tools. Exposures should be the Core side of that contract.
* The same reason we added `sources`: there's a big piece missing from the DAG today. Once downstream uses of dbt models are registered as `reports`, dbt project maintainers can start asking questions like:
    * Which models are our most critical dependencies?
    * Which final models are only used by exposures with very few/irregular views?
    * Which final models aren't used at all?

### Tentative spec
**Edit: updated based on comments below**

_models/anything.yml_
```yml
version: 2

exposures:
  - name: orders_dash

    type: dashboard # one of: {dashboard, notebook, analysis, ml, application}
    url: https://fishtown.looker.com/dashboards/1
    maturity: high # i.e. importance/usage/QA/SLA/etc. one of: {low, medium, high}

    description: >

      This is a dashboard of monthly orders, with customer
      attributes as context.

    depends_on:
      - ref('fct_orders')
      - ref('dim_customer')
      - source('marketplace', 'currency_conversions')

    owner:
      email: jeremy@fishtownanalytics.com # required
      name: "Jeremy from FP&A" # optional
```

### Core functionality

By way of `depends_on`, I'd expect `dbt run -m +report:orders_dash` to run all upstream models, and `dbt test -m +report:orders_dash` to test all upstream nodes. `dbt run -m +report:*` would run all models upstream of all reports. An report cannot itself be run or have tests defined.

**Edit:** I changed this syntax to feel more like the `source:` model selector method. Rationale: `dbt run -m orders_dash` has no effect; it's worth calling out that this is a special thing.

### Open questions

1. What should be the docs "landing page" for a `report`? I'll write up a related dbt-docs issue
2. Crucially, we'll need a mechanism that can parse a report's `depends_on` from `manifest.json`, compile the list of _all_ upstream nodes, and then search in `run_results.json` and `sources.json` for all associated tests and freshness checks. Where should that mechanism live, exactly?
3. `owner`: There is added benefit (and constraint) to tying this to a dbt Cloud user ID. Should we try to make a mapping via email only, instead?
4. `type` + `maturity`: Should we constrain the set of options here? Offer them as free text fields? I like the eventual idea of summarizing things like:
```
fct_orders is directly exposed in:
3 dashboards, of varying maturity (high: 2, medium: 1)
1 low-maturity ML pipeline
2 medium-maturity apps

fct_orders indirectly powers:
2 medium-maturity dashboards
```
Maybe that's in dbt-docs, maybe that's an `ls` command, maybe it's a pipe dream. This is the piece that feels least critical for the first version.

@drewbanin to help suss out some answers

### Future work (not v1)

* Can reports declare non-model nodes in their `depends_on`? (Could reports depend on _other_ reports?)
* Can reports modify expectations of upstream tests? I could imagine overriding a test severity, or defining a set of tests to exclude from consideration.
* Can reports be tagged?
* Can they accept arbitrary additional fields (i.e. `meta`)?
* Can we closely tie `owner` to a dbt Cloud user by email? Purpose: configurable notification channels, asset rendering in dbt-docs

**Comment by drewbanin** [comment]
> What should be the docs "landing page" for an exposure? I'll write up a related dbt-docs issue

Awesome! I think we can keep this pretty simple to start. Would be good to think about how they participate in the DAG view and what information we render on the Exposure details pages.

> Crucially, we'll need a mechanism that can parse an exposure's depends_on from manifest.json, compile the list of all upstream nodes, and then search in run_results.json and sources.json for all associated tests and freshness checks

I think this can be out-of-scope for dbt Core. Just producing a well-defined node in the manifest that contains edges out to specific nodes is going to be a great starting point. In this conversation, can we also consider _what_ an exposure can state dependencies on? Is it only models? Or are seeds/snapshots/sources also supported? I think you could make a convincing argument for either case!

> owner: There is added benefit (and constraint) to tying this to a dbt Cloud user ID. Should we try to make a mapping via email only, instead?

I think an optionality-preserving move would be to make the `owner` config a dict. Maybe something like:
```
owner:
  email: data-team@example.com

owner:
  name: Alice Dashmacher
  email: alice@example.com

owner:
  name: Alice Dashmacher
  email: alice@example.com
  slack: @aliced
```

Maybe we just make `email` required and leave room for other fields to be added in the future? You buy it?

> type + maturity: Should we constrain the set of options here? Offer them as free text fields?

If we're going to want to use this `type` info in structured ways, it will probably benefit us to restrict these to an enumerated set of values up-front. That said, I don't feel like we can close over the set of possible exposures that people are creating out there in the wild! My instinct is that we should start with a small set of `type` values (`{dashboard, notebook, analysis, ml, application}`) and plan to add more entries or make it free-text in the future if desired!

Do we love the label `maturity`? It's the name that seems most sensible to me, but I am unsure if encapsulates the entirety of importance/usage/SLAs/etc that we want it to convey. Maybe my fear would be overloading one label and trying to make it do too many things. If you've got other ideas, i'd love to discuss them, otherwise I think we should just pick sensible and roll with it!
