### ISSUE TITLE
Add default values for `--exclude` to `dbt_profile.yml`

### ISSUE THREAD

**Issue by tjwaterman99** [fishtown-analytics/dbt#2746]
### Describe the feature

I'd like to be able to skip building some models by default in my project's development environment.

For example, my team has a set of models under `models/tutorial` that are used to help onboard new users into the project. However, those models are not useful for the production schema or our documentation, and we'd like to exclude them.

One way to do this would be to add a `defaults` section to the `.dbt/profiles.yml` configuration.

```
# ./ci/.dbt/profiles.yml

myclient:
  defaults:
    exclude: models/tutorial
    threads: 8
    target: staging
  outputs:
    staging: &base
      type: snowflake
      account: ...
      user: ci
      schema: staging
      password: "{{ env_var('DBT_CI_USER_PASSWORD') }}"
      role: transformer
      database: analytics
      warehouse: transforming
      client_session_keep_alive: False

    public: 
      <<: *base
      schema: public
```

The `profiles.yml` file already has default parameter selections, namely the `--target` value and number of `--threads`. This would extend those defaults to another parameter: `--exclude`.

This pattern is also popular in other packages, such as pytest's configuration for [`addopts`](https://docs.pytest.org/en/stable/customize.html).

### Describe alternatives you've considered

- Maintaining a separate `dbt_project.yml` file for development environments with a separate `source-paths` value. But this solution meant we would need to maintain the all of the other values across both files, such as any data in the `vars` section, which isn't DRY.
- Building a wrapper around the `dbt` command, such as in `bin/dbt`, which did something like `dbt --exclude tutorial $@`. But that would be confusing for my team because they'd have to remember to use our custom `bin/dbt` command instead of the command referenced in all of DBT's documentation. I'm also not sure it would still allow them to use the `--exclude` flag themselves.

### Who will this benefit?

This benefits teams that want to maintain a production environment that doesn't include all of the models in their development environments.

### Are you interested in contributing this feature?

I would be happy to contribute! But this would be a large change to the `profiles.yml` file, so I wanted to see if others would benefit before seeing how far I could get.
