### ISSUE TITLE
Defining big query sources with characters in table name?

### ISSUE THREAD

**Issue by sgoley** [fishtown-analytics/dbt#2797]
After reviewing both of the below resources:

   - [Source configurations](https://docs.getdbt.com/reference/source-configs)
   - [BigQuery configurations](https://docs.getdbt.com/reference/resource-configs/bigquery-configs)

I was unable to find an answer to this question:

Given a standard dbt project directory, I am defining a `sources.yml` which points to pre-existing bigquery tables that contain character names.

`sources.yml`:

```
version: 2
sources:
    - name: biqquery
      tables: 
        - name: `fa--task.dataset.addresses`
        - name: `fa--task.dataset.devices`
        - name: `fa--task.dataset.orders`
        - name: `fa--task.dataset.payments`
```
Using tilde as in ` was successful directly from a select statement:

(select * from \`fa--task.dataset.orders\`)

but is not recognized as valid yaml in sources.

The desired result would be something like:

{{ sources('bigquery','\`fa--task.dataset.addresses\`') }}

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [X ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)
