### ISSUE TITLE
Relation doesn't exist for dbt test after `dbt run -m state:modified` if the test was modified but the model wasn't

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/dbt#2833]
### Describe the bug
Our Slim CI job runs 
```
dbt run -m state:modified
dbt test -m state:modified
```
(there are some additional exclusions to the `dbt test` arg, but they're not relevant here)

When I added another value to an accepted_values test, dbt identified that the test needed to be run, but it hadn't built the model during `dbt run` so I got this error
```
Database Error in test accepted_values_revenue__at_risk_by_day_at_risk_status__Lost__At_Risk__Large_Decrease__Strategic_Loss (models/marts/revenue/revenue.yml)
  relation "dbt_cloud_pr_5833_158.revenue__at_risk_by_day" does not exist
  compiled SQL at target/compiled/educationperfect/models/marts/revenue/revenue.yml/schema_test/accepted_values_revenue__at_risk_by_day_b3322b939ced8c28690422e1448abfc2.sql

```

### Steps To Reproduce
1. Change the existing test 
```

        - name: at_risk_status
          tests:
          - accepted_values:
              values: ['Lost', 'At Risk', 'Large Decrease']
```
to 
```

        - name: at_risk_status
          tests:
          - accepted_values:
              values: ['Lost', 'At Risk', 'Large Decrease', 'Strategic Loss']
```
and do 
```
dbt run -m state:modified
dbt test -m state:modified
```
### Expected behavior
The test to pass, because all values in the column are accepted

### Screenshots and log output
[dbt run debug.log](https://github.com/fishtown-analytics/dbt/files/5381717/dbt.run.debug.log)
[dbt run console.log](https://github.com/fishtown-analytics/dbt/files/5381718/dbt.run.console.log)
[dbt test console.log](https://github.com/fishtown-analytics/dbt/files/5381720/dbt.test.console.log)
[dbt test debug.log](https://github.com/fishtown-analytics/dbt/files/5381721/dbt.test.debug.log)

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Running with dbt=0.18.0
```

**The operating system you're using:**
dbt Cloud

**The output of `python --version`:**
