### ISSUE TITLE
Port cannot be set from an environment variable

### ISSUE THREAD

**Issue by moltar** [fishtown-analytics/dbt#2868]
### Describe the bug

Similarly to #2486, a port number cannot be provided via environment variable.

```yaml
default:
  outputs:
    production:
      type: postgres
      threads: 1
      host: "{{ env_var('DBT_HOST') }}"
      port: "{{ env_var('DBT_PORT') }}"
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASS') }}"
      dbname: "{{ env_var('DBT_DBNAME') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
  target: production
```

Results in:

>  Credentials in profile "default", target "production" invalid: '5432' is not of type 'integer'

### Steps To Reproduce

See above config.

### Expected behavior

Ability to pass port as env var.

### Screenshots and log output

See above.

### System information

**Which database are you using dbt with?**

- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**

Using Docker image `fishtownanalytics/dbt:0.18.1`.

**The operating system you're using:**

Using Docker image `fishtownanalytics/dbt:0.18.1`.

**The output of `python --version`:**

Using Docker image `fishtownanalytics/dbt:0.18.1`.

### Additional context

See #2486

**Comment by jtcohen6** [comment]
Hey @moltar, try adding the `as_number` filter, as shown in the [docs](https://docs.getdbt.com/reference/dbt-jinja-functions/as_number/):
```yml
default:
  outputs:
    production:
      type: postgres
      threads: 1
      host: "{{ env_var('DBT_HOST') }}"
      port: "{{ env_var('DBT_PORT') | as_number }}"
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASS') }}"
      dbname: "{{ env_var('DBT_DBNAME') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
  target: production
```
This was a breaking change in dbt v0.17.1 (#2618 to be precise).
