### ISSUE TITLE
[regression] Defining properties for model + exposure with same name raises exception

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt#2969]
### Describe the bug

dbt raises the exception `raise_duplicate_patch_name` when an exposure and a model have the same `name`:

https://github.com/fishtown-analytics/dbt/blob/ce6967d396f6723f44ad8d5efb058c760f27d167/core/dbt/parser/results.py#L156-L158

I've confirmed that this exception is _not_ raised by v0.18.1 or v0.19.0-b1 (the version we released on Oct 22), but it _is_ raised when I install dbt from the current development branch `dev/kiyoshi-kuromiya`.

### Steps To Reproduce

Create a model and an exposure with the same name, and define resource properties for both:
```yml
version: 2

models:
  - name: metrics
    description: My metrics model

exposures:
  - name: metrics
    type: dashboard
    description: My metrics dashboard
    depends_on:
      - ref('metrics')
    owner:
      email: data@acme.com
```

Try running any command, e.g. `dbt compile`:
```
  dbt found two schema.yml entries for the same resource named metrics. Resources and their associated columns may only be described a single time. To fix this, remove one of the resource entries for metrics in this file:
   - models/metrics/schema.yml
```

### Expected behavior
Since `exposures` are not included in the set of `nodes` (models, seeds, snapshots, tests) but rather their own resource type (like `sources`), it should be possible to define properties for an exposure and a model with the same name.

Otherwise, this will be a breaking change in v0.19.0.

**The output of `dbt --version`:**
```
$ dbt --version
installed version: 0.19.0-b1
```
i.e. current development version in `dev/kiyoshi-kuromiya`
