### ISSUE TITLE
Snowflake warehouse in dbt_project.yml models hierarchy does not apply to tests

### ISSUE THREAD

**Issue by zemekeneng** [fishtown-analytics/dbt#2981]
### Describe the bug
Snowflake warehouse in dbt_project.yml models hierarchy does not apply to tests. While `dbt run --models XXX` runs in the custom warehouse, `dbt test --models XXX` uses the warehouse specified in the profile/target.

### Steps To Reproduce
`dbt_project.yml`
```
models:
    my_project:
        my_model:
            +snowflake_warehouse: "custom_warehouse"
```
`~/.dbt/profiles.yml`
```
default:
  target: "{{ env_var('DBT_ENVIRONMENT', 'dev') }}"
  outputs:
    dev:
      type: snowflake
      account: my_sf_account
      user: "{{ env_var('DBT_USER') }}"
      role: "profile_role"

      private_key_path: "{{ env_var('PRIVATE_KEY_PATH') }}"
      private_key_passphrase: "{{ env_var('PRIVATE_KEY_PASSPHRASE') }}"

      database: "profile_db"
      schema: "public"
      warehouse: "profile_warehouse"
      threads: 1
      client_session_keep_alive: False
```

`models/my_model/model_one.sql`
```
select 1 one, 2 two, 3 three
```

`models/my_model/schema.yml`
```
version: 2
models:
  - name: model_one
    columns:
      - name: one 
        tests:
          - unique
```

```
dbt run --models my_model
dbt test --models my_model
```
### Expected behavior
The test should be run on `custom_warehouse`, not `profile_warehouse`.
I verify that the model is run with `custom_warehouse` but the test is run on `profile_warehouse` via snowflake history.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.18.1
   latest version: 0.18.1

Up to date!

Plugins:
  - snowflake: 0.18.1
  - bigquery: 0.18.1
  - postgres: 0.18.1
  - redshift: 0.18.1
```

**The operating system you're using:**
Debian GNU/Linux 10 (buster)
In a docker container
**The output of `python --version`:**
Python 3.8.5

**Comment by zemekeneng** [comment]
Maybe this is a feature request instead of a bug, but it would be nice to be able to define `snowflake_warehouse` independently for individual tests as is possible in the `{{ config }}` for models.

**Comment by jtcohen6** [comment]
Thanks for the write-up @zemekeneng! I agree, I think this would be an enhancement, and a good one at that.

Currently, the only supported config for all tests is `severity: warn|error`. I think it would make a lot of sense to support additional configs, including and not limited to ones like `enabled: true|false` and `snowflake_warehouse`.

Within a data test file:
```sql
{{ config(snowflake_warehouse = 'big') }}

select 1 as fun
```

For schema tests, within `models/*.yml` or `seeds/*.yml` or `snapshots/*.yml`:
```
version: 2

models:
  - name: my_model
    columns:
      - name: my_column
        tests:
          - unique:
            snowflake_warehouse: big
```

### Someday

In `dbt_project.yml` (post-#2401):
```yml
# for schema tests
models:
  my_project:
    some_models:
      +tests:
        snowflake_warehouse: big

# for data tests
tests:
  my_project:
    snowflake_warehouse: big
```

This type of inheritance would also be necessary if you wanted to override a config/property of a test defined in an installed package.

### Questions

_Should a schema test take its default value of `snowflake_warehouse` from the resource (model/seed/snapshot) on which it is defined?_

I'm inclined to say yes, though I also see a good reason in the opposite direction—that `snowflake_warehouse` should be treated as an exceptional override, not the rule, and only when warranted by especially heavy (materialization) queries. In any case, it should be possible to override this default for specific schema tests.

### Next steps

I'm going to add this to our v0.20 milestone, since we aim for that release to improve several of the current constraints and inconsistencies around tests.
