### ISSUE TITLE
Doc Inheritance

### ISSUE THREAD

**Issue by balmasi** [fishtown-analytics/dbt#2995]
### Describe the feature
I'm a big believer in the power of documentation, and I love dbt's doc generation, however, there is still a massive amount of manual work that goes into maintaining docs, especially if you have many layers, where many of the column descriptions aren't actually changing.

I'm finding I'm consistently spending 70% of my development time just wiring up documentation through doc blocks.

There are 3  cases that have to be accounted for with documentation (and tests, in fact):

1.  The names of the columns have not changed from upstream models
2. There has been a renaming of a column compared to an upstream model
3. There has been a meaningful transformation or additional column, compared to an upstream model

One can either address each of those concerns incrementally or come up with a solution that solves all 3.

## Ideal Solution

In an ideal world, all 3 issues could be solved if dbt could parse the SQL in all models using something like `sqlparse` to get true field-level lineage.

This could 
1. Inherit any docs in Case 1 or Case 2. 
2. Optionally Scaffold the description yml keys for Case 3, to be filled in by the user

This behaviour can be triggered using the CLI

```
# Option 1: new command to generate additional docs
dbt docs generate --inherit -m [models of interest]
```

I know this is a huge ask and involves major work, which is why I'm gonna put forward an incremental solution as well

## Incremental Solution

An easier-to-implement, but not as valuable solution would be to make this config-driven on a field by field basis. You still have to write quite a bit of boilerplate, but at least you're not copy-pasting (which leads to inconsistencies), or spinning up hundreds of `model.md` files to make doc block references (still very error-prone to get the doc block names right)

I'll include a `ref()` or `source()` for documentation purposes only, to demonstrate I'm talking about upstream models. but these can be just strings instead.

This might be something like:

```yml
# schema.yml
version: 2

models:
  - name: model_2
    description: "Unique description for model 2"
    columns:
      - name: col2
        description: '{{ doc_inherit(ref("upstream1") }}' # Case 1 - No change in column name, so we exclude the second argument

      - name: col1
        description: '{{ doc_inherit(source("src1"), "column_one"  }}'  # Case 2 - Col name was renamed

      - name: col3
        description: "This is brand new documentation" # Case 3 - Meaningful transformation or addition in this model
```

### Describe alternatives you've considered
Currently in order to solve this, I'm defining a new `.md` file for every model and using a `doc` reference in my schema.yml files. In order to keep things DRY and keep me sane, instead of referring to the immediate parent in every model, I refer to the ancestors (grandparents) of the model if possible.

For example, if  `source1 -> model1 -> model2 `all share a field name , model2 refers to the doc of `source1`  instead of model1. This way, I'm only changing descriptions in 1 place if the need arises.

### Who will this benefit?
I think implementing the **Ideal Solutoin** would have a major impact not only for speeding up documentation and keeping it up-to-date, but also allows you to apply the same strategy to **tests**, which is huge.

In the **Incremental Solution**, I'd say this would save me about 30-40% of my time for developing each feature. This is because I don't have to make additional `doc.md` files and don't have to worry about getting the `doc()` references correct, which can be a nightmare in a complex project.

I think if documentation (and maybe tests) are your thing, this solution would pave the way for saving tens of thousands of dollars over the life of a project in time saved.

### Are you interested in contributing this feature?
Maybe if I had a better idea of how dbt works under the hood based on a guide or something.

**Comment by balmasi** [comment]
Just realized the incremental solution is very close to https://github.com/fishtown-analytics/dbt/issues/1158

**Comment by jtcohen6** [comment]
@balmasi Thanks for this detailed writeup—I agree with a lot of what you've got to say here!

### Ideal Solution

I think this is what we're talking about when we're talking about **column-level lineage**, which is a sizzling topic these days. It would enable:
- dbt to know a column's properties (description, tests, `meta`, tags, etc) based on its upstream antecedents
- _You_ to ask and answer questions about how one column moves through the DAG

I think you're right on in outlining the prerequisite here:

> if dbt could parse the SQL in all models... We only need the SELECT [fields] and AS in the bottom-most expression

I think column-level lineage is the _real_ payoff of investing in SQL linting / auto-formatting (https://github.com/fishtown-analytics/dbt/issues/2356). It's a big part of the excitement around projects like [sqlfluff](https://github.com/sqlfluff/sqlfluff). The obvious (though hardly trivial!) short-term benefit is better-formatted code. The long game is that, by establishing and validating a grammar of SQL dialects, we could simply examine the compiled SQL of all the models in a project to know exactly how a given column moves through it. This won't be without significant complexity; the distinctions between parsed vs. compiled vs. executed code would need to be a lot clearer.

### Incremental Solution

I'm glad you came across #1158, which I've long thought of as "[YAML anchors](https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/) across file." Today, it's possible to do this at a basic level, using standard YAML anchors, within one `.yml` file:

```yml
version: 2

models:
  - name: model_1
    description: "Unique description for model 1"
    columns:
      - &col1
        name: col1
        description: "Unique description for column 1"
      - &col2
        name: col2
        description: "Unique description for column 2"
        tests:
          - unique
          - not_null

  - name: model_2
    description: "Unique description for model 2"
    columns:
      - <<: *col1
        name: column_one  # renamed
      - *col2  # inherits name, description, tests from model_1
      - name: col3
        description: "This is brand new documentation"
```

I see your `doc_inherit()` and the `extends:` proposal in the same vein here: a YAML anchor that can reference config defined in a different YAML file, elsewhere in the project.

**Comment by balmasi** [comment]
Wow thanks for the anchor tip. Didn't know I could do that.

I realised I was ridiculously naive about the difficulty of parsing sql from scratch 😅 takesy backsies

**Comment by jtcohen6** [comment]
Regarding this idea:

> a YAML anchor that can reference/alias/extend config defined in a different `.yml` file, elsewhere in the project.

See also the discussion in #1790, which proposes that we use a PyYAML (though not pure-YAML) construct to enable external file linking via an `!include` constructor.

**Comment by pcasteran** [comment]
I like the alternative syntax proposed by @balmasi. Until we have full support for column-level lineage, it allows to explicitly specify the column dependencies.

As I was looking for a way not to repeat the columns' documentation between all my models layers, I came to an almost identical solution (`ref` and `source` functions are not available in the templating context used for the documentation).

The idea is to add the `inherited_doc` method to the `DocsRuntimeContext` class (dbt/context/docs.py):
<details>

```python
    @contextmember
    def inherited_doc(self, **kwargs: Dict[str, Any]) -> str:
        """The `inherited_doc` function is used to reference another column's
        description. The column's description resolution is transitive,
        i.e. the referenced column's descritpion can also use the
        `inherited_doc` function.
        """

        # Retrieve the referenced node (model or source).
        node = None
        if "model" in kwargs:
            package_name = kwargs.get("package")
            model_name = kwargs["model"]
            node = self.manifest.resolve_ref(
                model_name,
                package_name,
                self._project_name,
                self.node.package_name,
            )
            if not node:
                raise_compiler_error(
                    "inherited_doc() : unable to find the referenced model : package=[{}], model=[{}]"
                        .format(package_name, model_name),
                    self.node
                )
        elif "source" in kwargs and "table" in kwargs:
            source_name = kwargs["source"]
            table_name = kwargs["table"]
            node = self.manifest.resolve_source(
                source_name,
                table_name,
                self._project_name,
                self.node.package_name,
            )
            if not node:
                raise_compiler_error(
                    "inherited_doc() : unable to find the referenced source : source=[{}], table=[{}]"
                        .format(source_name, table_name),
                    self.node
                )
        else:
            raise_compiler_error("Invalid use of the inherited_doc() function.", self.node)

        # Check if the column exists.
        if not "column" in kwargs:
            raise_compiler_error("Invalid use of the inherited_doc() function.", self.node)

        column_name = kwargs["column"]
        if not column_name in node.columns:
            raise_compiler_error("inherited_doc() : column '{}' doesn't not exist in the referenced model/source.".format(column_name), self.node)

        # Perform the transitive resolution of the referenced column's description.
        column = node.columns[column_name]
        try:
            description = get_rendered(column.description, self._ctx)
        except RecursionError:
            raise_compiler_error("inherited_doc() : circular dependencies encountered while resolving the description of column '{}'.".format(column_name),
                                 self.node)

        return description
```

</details>

It can then be used in the YAML files, for example:
```yaml
version: 2
models:
  - name: my_model
    description: Hello there
    columns:
      - name: id
        # Inheriting the description from another model.
        description: "{{ inherited_doc(model='my_other_model', column='id') }}"
      - name: name
        # Inheriting the description from a source.
        description: "{{ inherited_doc(source='my_source', table='my_table', column='name') }}"

```

It works fine for my project, but it has not been extensively tested (for example, models from another package).

Also, it correctly handles the transitive dependencies but without much intelligence about circular one : it just catches the `RecursionError` and raise a detailed dbt error.

What do you think about it @jtcohen6, is that something worth contributing ? I guess, it could easily be adapted to inherit column's tests.
