### ISSUE TITLE
Dbt details section is empty when using custom schema

### ISSUE THREAD

**Issue by Chayma-mesbahi** [fishtown-analytics/dbt#3012]
### Describe the bug
We are using custom schema;
In profile.yml, we specify the schema in the target. We overwrite this schema for some models. When the schema is customised, the detail section is not showing for models with customised schema.

#### Scenario 1 : When schema is NOT customised: 👍 
- What we have as a profile:
```my-bigquery-db:
  target: int
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: nx-formation-data-apache-beam
      dataset: prod_poc_dbt
      threads: 1
      timeout_seconds: 300
      priority: interactive
      retries: 1
    int:
      type: bigquery
      method: oauth
      project: nx-formation-data-apache-beam
      dataset: int_poc_dbt
      threads: 1
      timeout_seconds: 300
      priority: interactive
      retries: 1
 ```
-  The file **schema.yml** contains:
```
version: 2

models:
    - name: flights_per_carrier
    description: 'Number of flights per carrier'
    columns:
      - name: carrier_id
        tests:
          - relationships:
              to: ref('carriers')
              field: carrier_id
          - not_null
      - name: carrier_name
        tests:
          - relationships:
              to: ref('carriers')
              field: carrier_name
      - name: n_flights
   - name: enriched_flights
    description: "Enriched flights data"
```
- In this case, as shown in the photo, the docs shows the description and the tests declared in the **schema.yml**:
<img width="1440" alt="Capture d’écran 2021-01-14 à 16 30 53" src="https://user-images.githubusercontent.com/66114317/104612434-7ac0e380-5686-11eb-84b2-46e3b052dd13.png">

#### Scenario 2 : When schema is customised: 👎 
- We keep the same profile configuration as above:
```my-bigquery-db:
  target: int
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: nx-formation-data-apache-beam
      dataset: prod_poc_dbt
      threads: 1
      timeout_seconds: 300
      priority: interactive
      retries: 1
    int:
      type: bigquery
      method: oauth
      project: nx-formation-data-apache-beam
      dataset: int_poc_dbt
      threads: 1
      timeout_seconds: 300
      priority: interactive
      retries: 1
 ```
- We use this macros to customise schema:
```
{% macro generate_dataset_name(name) -%}
  
    {{ target.name + "_" + name }} 
  
{%- endmacro %}
```
- This macro is called in each model configuration, for example  the model **models/transform/flights_per_carrier.sql**:
```
{{ config(
  materialized = "view",
  schema = generate_dataset_name("carrier")
) }}

select
    carrier_id,
    carrier_name,
    count(*) as n_flights
from 
    {{ ref('enriched_flights' )}}
group by
    carrier_id, carrier_name 
order by 
    n_flights desc 
```
- Now we change the file **schema.yml** so these changes can be taken into account:
```
version: 2

models:
  - name: |
      {%- if  target.name == "int" -%} int_poc_dbt_int_carrier
      {%- elif target.name == "prod" -%} prod_poc_dbt_int_carrier
      {%- else -%} invalid_dataset
      {%- endif -%}
    tables:
    - name: flights_per_carrier
      description: 'Number of flights per carrier'
      columns:
        - name: carrier_id
          tests:
            - relationships:
                to: ref('carriers')
                field: carrier_id
            - not_null
        - name: carrier_name
          tests:
            - relationships:
                to: ref('carriers')
                field: carrier_name
        - name: n_flights
  - name: |
      {%- if  target.name == "int" -%} int_poc_dbt_int_enriched
      {%- elif target.name == "prod" -%} prod_poc_dbt_int_enriched
      {%- else -%} invalid_dataset
      {%- endif -%}
      
    tables:
      - name: enriched_flights
        description: "Enriched flights"

```
- As shown in the photo, the customisation works, but there are neither description nor tests:
<img width="1440" alt="Capture d’écran 2021-01-14 à 16 52 16" src="https://user-images.githubusercontent.com/66114317/104614872-ef951d00-5688-11eb-908a-0456450ffdae.png">

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```installed version: 0.18.1
   latest version: 0.18.1

Up to date!

Plugins:
  - bigquery: 0.18.1
  - snowflake: 0.18.1
  - redshift: 0.18.1
  - postgres: 0.18.1
```

**The operating system you're using:**
Mac OS
**The output of `python --version`:**
``` Python 3.8.5 ```
### Additional context
Similar issue was found on stackoverflow but not resolved: https://stackoverflow.com/questions/63079113/dbt-docs-detailed-section-is-empty-when-using-custom-schema

**Comment by jtcohen6** [comment]
Hey @Chayma-mesbahi, thanks for the details above. A few things stuck out to me:

1. The changes to `schema.yml` don't make sense to me, and I don't think they're necessary. Instead, you can keep the original `schema.yml` specification exactly as it was:

```yml
version: 2

models:
  - name: flights_per_carrier
    description: 'Number of flights per carrier'
    columns:
      - name: carrier_id
        tests:
          - relationships:
              to: ref('carriers')
              field: carrier_id
          - not_null
      - name: carrier_name
        tests:
          - relationships:
              to: ref('carriers')
              field: carrier_name
      - name: n_flights
  - name: enriched_flights
    description: "Enriched flights data"
```
dbt knows the names of these models are `flights_per_carrier` and `enriched_flights`, even if you've also configured custom schemas/aliases to change how they appear in BigQuery. Basically I disagree with your statement:

> Now we change the file schema.yml so these changes can be taken into account:

dbt will take them into account on your behalf. No changes necessary on your part. It's possible that tests and descriptions aren't showing up because the code snippet you pasted is not a valid YAML structure.

2.. Instead of coding up a `generate_database_name()` macro and passing it to the `schema` config of each model, you could instead create a [`generate_schema_name` macro](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-schemas/#generate_schema_name-arguments)—something dbt knows to look for, and knows how to use—like so:

 ```sql
 {% macro generate_schema_name(custom_schema_name, node) -%}
  
    {{ target.name + "_" + custom_schema_name }} 
  
{%- endmacro %}
```

Then your model can just be:
```sql
{{ config(
  materialized = 'view',
  schema = 'carrier'
) }}

select
    carrier_id,
    carrier_name,
    count(*) as n_flights
from 
    {{ ref('enriched_flights' )}}
group by
    carrier_id, carrier_name 
order by 
    n_flights desc 
```

Leave your YAML in place, and everything should work the way you expect.

I'm going to close this issue, since I don't believe it to engender a code change in dbt. Feel free to continue commenting below if you have questions or think that I may have missed something.
