### ISSUE TITLE
can't install from dbt-hub package versions like 0.6.4.1

### ISSUE THREAD

**Issue by swanderz** [fishtown-analytics/dbt#3109]
### Describe the bug
If you try and install [tsql-utils](https://github.com/dbt-msft/tsql-utils) with a `packages.yml` below, it returns this error
> "Could not parse version "0.6.4.1"

```
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.4
  - package: dbt-msft/tsql_utils
    version: 0.6.4.1
```

thanks @datasharkNL [for flagging](https://getdbt.slack.com/archives/C01DRQ178LQ/p1613552327021500?thread_ts=1613492776.018700&cid=C01DRQ178LQ)!
