### ISSUE TITLE
Relationship tests rendering in docs on the `to` model instead of the model the test was defined in

### ISSUE THREAD

**Issue by mascah** [fishtown-analytics/dbt#3180]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

`relationships` tests are rendering on the `to` model docs instead of the model that the test was defined in.

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

1. dbt init a new project
1. add a relationship test to the example `my_second_dbt_model.sql`

```
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
                - relationships:
                    to: ref('my_first_dbt_model')
                    field: id
```

1. dbt docs generate
1. dbt docs serve

![image](https://user-images.githubusercontent.com/6239162/111786672-ada07700-8883-11eb-9d9c-899ddab8b972.png)

### Expected behavior

The relationship test renders on in the model that the test was defined in. Otherwise, if I have a table that has foreign keys in many other tables (i.e. date dimension), they will all show up on the date dimension, which isn't as useful as if the foreign key relationship showed in the model it was defined in, i.e. a fact table.

The current behavior is also unusual from a user perspective, because foreign keys in a traditional RDBMS are defined on the the foreign table, pointing to the parent table. 

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
dbt --version
installed version: 0.19.0
   latest version: 0.19.0

Up to date!

Plugins:
  - bigquery: 0.19.0
  - snowflake: 0.19.0
  - redshift: 0.19.0
  - postgres: 0.19.0
```

**The operating system you're using:** 

macOS 10.15.6

**The output of `python --version`:**

3.8.1
