### ISSUE TITLE
BigQuery project reversion in 0.19.1

### ISSUE THREAD

**Issue by max-sixty** [fishtown-analytics/dbt#3218]
### Describe the bug

0.19.1 reverts the behavior around whether a `database` / `project` is required in `profiles.yml`.

For example:

```yaml
foo:
  target: user
  outputs:
    user:
      type: bigquery
      method: oauth
      dataset: max
      timeout_seconds: 3600
      threads: 24
      # project: x
```

...fails with 

```
Encountered an error:
Field "database" of type typing.Union[str, NoneType] is missing in dbt.adapters.bigquery.connections.BigQueryCredentials instance
```

Un-commenting `project` above works.

### Expected behavior

As above, which worked in 0.19.0

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.19.1
   latest version: 0.19.1

Up to date!

Plugins:
  - bigquery: 0.19.1
  - snowflake: 0.19.1
  - redshift: 0.19.1
  - postgres: 0.19.1
```

**The operating system you're using:**
MacOS
**The output of `python --version`:**
3.8

**Comment by jtcohen6** [comment]
@max-sixty You're right—I'm sorry I didn't catch this during the v0.19.1 testing process.

Let's figure out a fix for this, and a way to add an automated test for this—even if we can't fully integration-test it (since the integration tests run via service account)—to ensure that this doesn't happen again in a future version.

**Comment by jtcohen6** [comment]
So this still works:
```yml
my-bigquery:
  outputs:
    oauth:
      type: bigquery
      method: oauth
      project: "{{ 'None' | as_native }}"
      dataset: dbt_jcohen
  target: oauth
```
The `project` field is indeed allowed to be `None`, and when it is, dbt will use the `gcloud`-configured default project (per the work in https://github.com/fishtown-analytics/dbt/pull/2908). The issue is when `project` is missing entirely, it raises this error:
```
Field "database" of type typing.Union[str, NoneType] is missing in dbt.adapters.bigquery.connections.BigQueryCredentials instance
```
