### ISSUE TITLE
Support `enabled` configuration for generic tests

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt#3252]
Today, it is possible to disable a one-off test by including `{{ config(enabled = false) }}` in its `.sql` file.

1. Make it possible to disable specific instances of generic tests via an `enabled` configuration/argument:
```yml
models:
  - name: model_a
    columns:
      - name: id
        tests:
          - unique:
              enabled: false
```

2. Make it possible to disable all instances of a generic test:
```sql
{% test not_null(model, column_name), adapter = 'default' %}

    {{ config(enabled = false) }}

    select * from {{ model }}
    where {{ column_name }} is null

{% endtest %}
```

To be clear: Achieving item 2 is less important than item 1. The idea here is _not_ that the `not_null` "test macro" is itself disabled and missing from the project, but rather that all specific instances of the `not_null` test inherit the default configuration/argument of `enabled = false`. It's a matter of convenience, more than anything.

_Note: The ability to set "default" behavior for custom schema tests, by including `config()` in the test definition, was an undocumented (though reasonable) feature. There is a regression for it in v0.19.1. See #3240._
