### ISSUE TITLE
Redshift IAM Authentication docs mistake

### ISSUE THREAD

**Issue by marcin-j** [fishtown-analytics/dbt#3285]
### Describe the bug
There is a mistake in Redshift profiles.yml configuration docs. In ﻿﻿[IAM Authentication#](https://docs.getdbt.com/reference/warehouse-profiles/redshift-profile#iam-authentication) section "cluster_id" configuration key should NOT be wrapped in "[]" array notation.

**Comment by jtcohen6** [comment]
Thanks @marcin-j! I'm going to transfer this issue over to the docs.getdbt.com repo, which has the code for the documentation website. If you'd like to contribute the fix, you can [edit the page](https://github.com/fishtown-analytics/docs.getdbt.com/edit/current/website/docs/reference/warehouse-profiles/redshift-profile.md) directly in the GitHub UI.

I see the confusion here. The `[]` notation was not meant to indicate that this is an array value, but rather that you should fill it in with your own actual cluster ID. That's confusing because (a) the other profile attributes in that example _are_ filled in with made-up values, and (b) `db_groups` really is an array! More generally, we could consider switching `[]` for `<>` as the notation meaning, "Your real value goes here." So like:
```yml
my-redshift-db:
  target: dev
  outputs:
    dev:
      type: redshift
      method: iam
      cluster_id: <cluster_id>
      host: <host>
      user: <user>
      iam_profile: <profile> # optional
      iam_duration_seconds: <1234>  # optional
      autocreate: <true | false>           # optional
      db_groups: ['<groupname>']    # optional
```
