### ISSUE TITLE
Missing output of `meta` in resource files

### ISSUE THREAD

**Issue by buremba** [fishtown-analytics/dbt#3301]
### Describe the bug

As you see, `{{this}}` keyword is removed in the output metadata, is this expected?
I don’t think that dbt compiles YML files via jinja2 because `{%` tags don't compile but I may be missing something here.

### Steps To Reproduce

1. Create a file `models/source.yml` as follows:

```
version: 2

sources:
  - name: jaffle_shop
    tables:
      - name: orders
         meta:
             test: "value{{this}}"
```

1. Run `dbt list`
2. Open `manifest.json` file and you will see the following output of `meta` for `jaffle_shop.orders` source:

```
"meta": {"test": {"value"}}
```

### Expected behavior

It should have the following output:

```
"meta": {"test": {"test": "value{{this}}"}}
```

### System information
**Which database are you using dbt with?**
- [ x] postgres

**The output of `dbt --version`:**
```
0.19.1
```

**The operating system you're using:**
```
Mac OS
```

**The output of `python --version`:**
```
Python 3.8.6
```
