### ISSUE TITLE
[BQ] Policy tag missing after model run

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt#3304]
### Steps to reproduce

Add the following roles in IAM to the dbt service account:
- Data Catalog Admin
- Policy Tag Admin
- Fine-Grained Reader
- BigQuery Data Owner

In `dbt_project.yml`, add:
```yml
models:
  +persist_docs:
    relation: true
    columns: true

vars:
  policy_tag_ids:
    pt_name: 'projects/my-project/locations/<location>/taxonomies/<organization>/policyTags/<tag>'
```
In `schema.yml`, add:
```yml
models:
  - name: my_model
    columns:
      - name: name
        policy_tags:
          - '{{ var("policy_tag_ids")["pt_name"] }}'
```

```
$ dbt run -m my_model
```

### Expected Result

Column-level policy tag on the `my_model` table in BigQuery’s schema tab.

### Actual result

Nothing shows.

### Log output

In the BigQuery cloud audit logs (both data access and activity), there isn’t any mention of policy tags.

### System information

- BigQuery
- dbt version: 0.18.1

### Additional context

From the [original pull request](https://github.com/fishtown-analytics/dbt/pull/2589/files#diff-1721f193734dd76549482de07fbb160112058ef2ccba30ac8e57ecfd46f3159c) that implemented this functionality, the test class seems to follow the same steps as the ones taken.
