### ISSUE TITLE
Non-additive tags

### ISSUE THREAD

**Issue by jtalmi** [fishtown-analytics/dbt#3326]
### Describe the feature
Because tags are additive, we've chosen to group models into subfolders based on their tag. For example, your folder structure may look like this:

```
finance /
  hourly /
    mymodel.sql
  nightly /
    mymodel2.sql
```
The dbt project yml looks like this:

```
finance:
  hourly:
    tags: hourly
  nightly:
   tags: nightly
```

Without the subfolders, we've to assign tags like so:

```
finance:
  mymodel1:
    tags: hourly
  mymodel2:
    tags: nightly
```

This doesn't scale well. It would be great if we could set a default tag for a folder, let's say `nightly`, but override that tag for specific models or subfolders. That would help us declutter our dbt_project.yml and make it easier to contribute new models or change them.

### Describe alternatives you've considered
The alternative is a complex folder structure, grouping models by tags, or simply specifying a config for every model.

### Additional context
Not sure this is even possible in YAML

### Who will this benefit?
All dbt users. Many users use tags for deployment, e.g. `dbt run -m tag:hourly` or `dbt run -m tag:nightly`. This would help us avoid collisions which result in rerunning the same models in multiple places.

### Are you interested in contributing this feature?
Sure!
