### ISSUE TITLE
Default arg values ignored in test block signature

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt#3329]
### Describe the bug

Previously, when schema tests were macros prefixed `test_`, it was possible to set default values for arguments within the macro signature. Now that ~schema~ generic tests are special test blocks, it would be ideal to still set default values in the signature. Worst case, there is a way of working around it via `kwargs.get`, but this represents a more serious breaking change and more time-consuming upgrade path for existing packages + projects.

### Steps To Reproduce

```sql
{% test my_signature_test(model, default_arg = 'default value') %}
    select '{{ default_arg }}'
{% endtest %}

{% test my_kwargy_test(model) %}
    {% set default_arg = kwargs.get('default_arg', 'default value') %}
    select '{{ default_arg }}'
{% endtest %}
```

```
version: 2

models:
  - name: my_model
    tests:
      - my_signature_test
      - my_kwargy_test
      - my_signature_test:
          default_arg: override value
      - my_kwargy_test:
          default_arg: override value
```

When I run `dbt test`, the test output looks like (in order of the above):
```
select ''
select 'default value'
select 'override value'
select 'override value'
```

### Expected behavior

The default values for arguments in the `test` block signature should be used if no user-supplied argument is provided.

### System information

**The output of `dbt --version`:**
```
$ dbt --version
installed version: 0.20.0-b1
   latest version: 0.19.1

Your version of dbt is ahead of the latest release!

Plugins:
  - bigquery: 0.20.0b1
  - snowflake: 0.20.0b1
  - redshift: 0.20.0b1
  - postgres: 0.20.0b1
```
