### ISSUE TITLE
dbt profiles target name set to: default raises: INVALID_DATABASE when running dbt docs generate

### ISSUE THREAD

**Issue by czardien** [fishtown-analytics/dbt#3355]
### Describe the bug

This is a very very odd one, and I might have missed something in the docs so please bear with me! I am deploying a dbt service and I have the following `profiles.yml` file in: `/etc/dbt`:

```
default:                                                                                                                                                                                                                                                                          
  target: default                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                  
  outputs:                                                                                                                                                                                                                                                                        
    default:                                                                                                                                                                                                                                                                         
      type: snowflake                                                                                                                                                                                                                                                             
      account: uk<something>.eu-west-1                                                                                                                                                                                                                                                  
      user: TRANSFORM_DBT                                                                                                                                                                                                                                                         
      password: <password>                                                                                                                                                                                                                          
      role: TRANSFORM_DBT                                                                                                                                                                                                                                                         
      database: MY_WAREHOUSE                                                                                                                                                                                                                                                     
      warehouse: TRANSFORM_DBT                                                                                                                                                                                                                                                    
      schema: PUBLIC                                                                                                                                                                                                                                                              
      threads: 1                                                                                                                                                                                                                                                                  
      client_session_keep_alive: False                                                                                                                                                                                                                                            
      query_tag: "dbt_default"
```

Using this profile, running:

```
$ DBT_PROFILES_DIR=/etc/dbt dbt docs generate
```

... raises the following error:

```
Running with dbt=0.19.0
Found 11 models, 0 tests, 0 snapshots, 0 analyses, 315 macros, 0 operations, 0 seed files, 1 source, 0 exposures

11:34:37 | Concurrency: 1 threads (target='default')
11:34:37 | 
11:34:38 | Done.
11:34:38 | Building catalog
Encountered an error while generating catalog: Database Error
  002003 (02000): SQL compilation error:
  Database 'INVALID_DATABASE' does not exist or not authorized.
dbt encountered 1 failure while writing the catalog
11:34:42 | Catalog written to /var/lib/dbt/target/catalog.json
```

... with logs from: `logs/dbt.logs`:

```
[...]
      select *                                                                                                                                                                                                                                                                    
      from tables                                                                                                                                                                                                                                                                 
      join columns using ("table_database", "table_schema", "table_name")                                                                                                                                                                                                         
      where (upper("table_schema") = upper('public'))                                                                                                                                                                                                                             
      order by "column_index"                                                                                                                                                                                                                                                     
2021-05-14 11:36:47.774934 (ThreadPoolExecutor-1_0): Opening a new connection, currently in state init                                                                                                                                                                            
2021-05-14 11:36:49.975603 (ThreadPoolExecutor-1_0): SQL status: SUCCESS 930 in 2.20 seconds                                                                                                                                                                                      
2021-05-14 11:36:50.413449 (ThreadPoolExecutor-1_0): On MY_DATABASE.information_schema: Close                                                                                                                                                                                     
2021-05-14 11:36:50.467244 (ThreadPoolExecutor-1_0): Acquiring new snowflake connection "invalid_database.information_schema".                                                                                                                                                    
2021-05-14 11:36:50.471978 (ThreadPoolExecutor-1_0): Using snowflake connection "invalid_database.information_schema".                                                                                                                                                            
2021-05-14 11:36:50.472101 (ThreadPoolExecutor-1_0): On invalid_database.information_schema: /* {"app": "dbt", "dbt_version": "0.19.0", "profile_name": "default", "target_name": "default", "connection_name": "invalid_database.information_schema"} */
[...]
```

... before it errors out a few messages down. Below is the full log. As you can see, there is some dodgy thing happening when a happy connection and query is made against the expected: `MY_WAREHOUSE` database, before acquiring a new Snowflake connection to: `invalid_database`. I checked our code-base few times, there is no mention of the identifier: `invalid_database` anywhere.

Please note at this point that running: `$ dbt docs serve` will actually serve this expected docs, even though the generation errored!

Now, if I change my `profiles.yml` to: 

```
default:                                                                                                                                                                                                                                                                          
  target: prod                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                  
  outputs:                                                                                                                                                                                                                                                                        
    prod:                                                                                                                                                                                                                                                                         
      type: snowflake                                                                                                                                                                                                                                                             
      account: uk<something>.eu-west-1                                                                                                                                                                                                                                                  
      user: TRANSFORM_DBT                                                                                                                                                                                                                                                         
      password: <password>                                                                                                                                                                                                                          
      role: TRANSFORM_DBT                                                                                                                                                                                                                                                         
      database: <somewarehouse>                                                                                                                                                                                                                                                       
      warehouse: TRANSFORM_DBT                                                                                                                                                                                                                                                    
      schema: PUBLIC                                                                                                                                                                                                                                                              
      threads: 1                                                                                                                                                                                                                                                                  
      client_session_keep_alive: False                                                                                                                                                                                                                                            
      query_tag: "dbt_default"
```

... the error disappears and: `$ DBT_PROFILES_DIR=/etc/dbt dbt docs generate` runs fine.

How weird is that? 

### Steps To Reproduce
See above.

### Expected behavior

```
$ dbt docs generate
```

... runs fine with a target name set to: `default`, or the error message is more explicit (if there's an error, as I said we can further run: `dbt docs serve` despite the error).

### Screenshots and log output

```
[...]
2021-05-14 11:36:47.560728 (MainThread): Connection 'model.<id>.fct_<id>' was properly closed.                                                                                                                                                                 
2021-05-14 11:36:47.724142 (MainThread): 11:36:47 | Done.                                                                                                                                                                                                                         
2021-05-14 11:36:47.726223 (MainThread): Acquiring new snowflake connection "generate_catalog".                                                                                                                                                                                   
2021-05-14 11:36:47.726346 (MainThread): 11:36:47 | Building catalog                                                                                                                                                                                                              
2021-05-14 11:36:47.764867 (ThreadPoolExecutor-1_0): Acquiring new snowflake connection "MY_WAREHOUSE.information_schema".                                                                                                                                                         
2021-05-14 11:36:47.774697 (ThreadPoolExecutor-1_0): Using snowflake connection "MY_WAREHOUSE.information_schema".                                                                                                                                                                 
2021-05-14 11:36:47.774849 (ThreadPoolExecutor-1_0): On MY_WAREHOUSE.information_schema: /* {"app": "dbt", "dbt_version": "0.19.0", "profile_name": "default", "target_name": "default", "connection_name": "MY_WAREHOUSE.information_schema"} */                                   
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                  
      with tables as (                                                                                                                                                                                                                                                            

          select                                                                                                                                                                                                                                                         [60/1773]
              table_catalog as "table_database",                                                                                                                                                                                                                                  
              table_schema as "table_schema",                                                                                                                                                                                                                                     
              table_name as "table_name",                                                                                                                                                                                                                                         
              table_type as "table_type",                                                                                                                                                                                                                                         
              comment as "table_comment",                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                  
              -- note: this is the _role_ that owns the table                                                                                                                                                                                                                     
              table_owner as "table_owner",                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                  
              'Clustering Key' as "stats:clustering_key:label",                                                                                                                                                                                                                   
              clustering_key as "stats:clustering_key:value",                                                                                                                                                                                                                     
              'The key used to cluster this table' as "stats:clustering_key:description",                                                                                                                                                                                         
              (clustering_key is not null) as "stats:clustering_key:include",                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                  
              'Row Count' as "stats:row_count:label",                                                                                                                                                                                                                             
              row_count as "stats:row_count:value",                                                                                                                                                                                                                               
              'An approximate count of rows in this table' as "stats:row_count:description",                                                                                                                                                                                      
              (row_count is not null) as "stats:row_count:include",                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                  
              'Approximate Size' as "stats:bytes:label",                                                                                                                                                                                                                          
              bytes as "stats:bytes:value",                                                                                                                                                                                                                                       
              'Approximate size of the table as reported by Snowflake' as "stats:bytes:description",                                                                                                                                                                              
              (bytes is not null) as "stats:bytes:include",                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                  
              'Last Modified' as "stats:last_modified:label",                                                                                                                                                                                                                     
              to_varchar(convert_timezone('UTC', last_altered), 'yyyy-mm-dd HH24:MI'||'UTC') as "stats:last_modified:value",                                                                                                                                                      
              'The timestamp for last update/change' as "stats:last_modified:description",                                                                                                                                                                                        
              (last_altered is not null and table_type='BASE TABLE') as "stats:last_modified:include"                                                                                                                                                                             
                                                                                                                                                                                                                                                                                  
          from MY_WAREHOUSE.INFORMATION_SCHEMA.tables                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                  
      ),                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                  
      columns as (                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                  
          select                                                                                                                                                                                                                                                                  
              table_catalog as "table_database",                                                                                                                                                                                                                                  
              table_schema as "table_schema",                                                                                                                                                                                                                                     
              table_name as "table_name",                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                  
              column_name as "column_name",                                                                                                                                                                                                                                       
              ordinal_position as "column_index",                                                                                                                                                                                                                                 
              data_type as "column_type",                                                                                                                                                                                                                                         
              comment as "column_comment"                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                  
          from MY_WAREHOUSE.INFORMATION_SCHEMA.columns                                                                                                                                                                                                                             
      )                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                  
      select *                                                                                                                                                                                                                                                                    
      from tables                                                                                                                                                                                                                                                                 
      join columns using ("table_database", "table_schema", "table_name")                                                                                                                                                                                                         
      where (upper("table_schema") = upper('public'))                                                                                                                                                                                                                             
      order by "column_index"                                                                                                                                                                                                                                                     
2021-05-14 11:36:47.774934 (ThreadPoolExecutor-1_0): Opening a new connection, currently in state init                                                                                                                                                                            
2021-05-14 11:36:49.975603 (ThreadPoolExecutor-1_0): SQL status: SUCCESS 930 in 2.20 seconds                                                                                                                                                                                      
2021-05-14 11:36:50.413449 (ThreadPoolExecutor-1_0): On MY_WAREHOUSE.information_schema: Close                                                                                                                                                                                     
2021-05-14 11:36:50.467244 (ThreadPoolExecutor-1_0): Acquiring new snowflake connection "invalid_database.information_schema".                                                                                                                                                    
2021-05-14 11:36:50.471978 (ThreadPoolExecutor-1_0): Using snowflake connection "invalid_database.information_schema".                                                                                                                                                            
2021-05-14 11:36:50.472101 (ThreadPoolExecutor-1_0): On invalid_database.information_schema: /* {"app": "dbt", "dbt_version": "0.19.0", "profile_name": "default", "target_name": "default", "connection_name": "invalid_database.information_schema"} */
    with tables as (

          select
              table_catalog as "table_database",
              table_schema as "table_schema",
              table_name as "table_name",
              table_type as "table_type",
              comment as "table_comment",

              -- note: this is the _role_ that owns the table
              table_owner as "table_owner",

              'Clustering Key' as "stats:clustering_key:label",
              clustering_key as "stats:clustering_key:value",
              'The key used to cluster this table' as "stats:clustering_key:description",
              (clustering_key is not null) as "stats:clustering_key:include",

              'Row Count' as "stats:row_count:label",
              row_count as "stats:row_count:value",
              'An approximate count of rows in this table' as "stats:row_count:description",
              (row_count is not null) as "stats:row_count:include",

              'Approximate Size' as "stats:bytes:label",
              bytes as "stats:bytes:value",
              'Approximate size of the table as reported by Snowflake' as "stats:bytes:description",
              (bytes is not null) as "stats:bytes:include",

              'Last Modified' as "stats:last_modified:label",
              to_varchar(convert_timezone('UTC', last_altered), 'yyyy-mm-dd HH24:MI'||'UTC') as "stats:last_modified:value",
              'The timestamp for last update/change' as "stats:last_modified:description",
              (last_altered is not null and table_type='BASE TABLE') as "stats:last_modified:include"

          from invalid_database.INFORMATION_SCHEMA.tables

      ),

      columns as (

          select
              table_catalog as "table_database",
              table_schema as "table_schema",
              table_name as "table_name",

              column_name as "column_name",
              ordinal_position as "column_index",
              data_type as "column_type",
              comment as "column_comment"

          from invalid_database.INFORMATION_SCHEMA.columns
      )

      select *
      from tables
      join columns using ("table_database", "table_schema", "table_name")
      where (upper("table_schema") = upper('public'))
      order by "column_index"
2021-05-14 11:36:50.472188 (ThreadPoolExecutor-1_0): Opening a new connection, currently in state closed
2021-05-14 11:36:50.821911 (ThreadPoolExecutor-1_0): Snowflake query id: 019c3d58-3200-95b3-0000-9f2d001adbc6
2021-05-14 11:36:50.822054 (ThreadPoolExecutor-1_0): Snowflake error: 002003 (02000): SQL compilation error:
Database 'INVALID_DATABASE' does not exist or not authorized.
2021-05-14 11:36:50.822185 (ThreadPoolExecutor-1_0): Error running SQL: macro get_catalog
2021-05-14 11:36:50.822238 (ThreadPoolExecutor-1_0): Rolling back transaction.
2021-05-14 11:36:50.822327 (ThreadPoolExecutor-1_0): On invalid_database.information_schema: Close
2021-05-14 11:36:50.877431 (MainThread): Encountered an error while generating catalog: Database Error
  002003 (02000): SQL compilation error:
  Database 'INVALID_DATABASE' does not exist or not authorized.
2021-05-14 11:36:51.581684 (MainThread): dbt encountered 1 failure while writing the catalog
2021-05-14 11:36:51.581991 (MainThread): 11:36:51 | Catalog written to /var/lib/dbt/target/catalog.json
2021-05-14 11:36:51.583762 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3fd8a488e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3fd240a7f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3fd27f0c70>]}
2021-05-14 11:36:51.584110 (MainThread): Flushing usage events
2021-05-14 11:36:51.974201 (MainThread): Connection 'generate_catalog' was properly closed.
2021-05-14 11:36:51.974678 (MainThread): Connection 'invalid_database.information_schema' was properly closed.

```

... I have some of our identifiers up there so I truncated the logs, let me know if you'd like more but I feel like the fishy things are happening in there, when the connection switches from: `MY_WAREHOUSE` to: `INVALID_DATABASE`.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)


**The output of `dbt --version`:**
```
0.19.0
```

... but I tried with: `0.19.1` with the same output.

**The operating system you're using:**

Ubuntu 20.04

**The output of `python --version`:**

3.8

Edit: Typos and Ubuntu version
