### ISSUE TITLE
Unexpected trigger of downstream data tests when the model is used as an argument of those data tests

### ISSUE THREAD

**Issue by Shadowsong27** [fishtown-analytics/dbt#3382]
### Describe the bug

Hello folks.

Say we have 2 models.

view_down
```
models:
  - name: view_down
    columns:
      - name: dw_address_id
         tests:
          - unique
    tests:
      - two_tables_change_count:
          threshold: '50'
          other_model: ref('view_up')
```

and 

view_up
```
models:
  - name: view_up
    columns:
      - name: 'postal_code'
        tests:
          - not_null
```

definition of `two_tables_change_count`, it compares row diff based on conditions

```
{% macro test_two_tables_change_count(model, result_type, dir, threshold, other_model='', dim_raw={}, dim_res={}) %}

with base AS (
   select (
        select count(*)
        from {{ other_model }}
        where 1=1
        {{ generate_cond_clause_from_dict(dim_raw) }}
    ) raw_count,
   (
        select count(*)
        from {{ model }}
        where 1=1
        {{ generate_cond_clause_from_dict(dim_res) }}
   ) result_count
),

{{ generate_two_result_compare_clause(dir, threshold, result_type) }}

{% endmacro %}
```

When executing `data test -m view_up`, it will also trigger the data test of `view_down` - `two_tables_change_count`, which is unexpected to me. 

This is not very desirable for us coz view_up is an upstream task of view_down, and when 
we are following this pattern `run view_up -> test view_up -> run view_down -> test view_down`,
we definitely do not want to have a failed `test view_up` command caused by the failure of one of the `view_down` data tests, since the `run view_down` has not been executed yet.

We have curerntly bypassed this by not declaring an actual model as an
test argument, but rather the model name - which is not very elegant.

so something like this 

```
models:
  - name: view_down
    columns:
      - name: dw_address_id
         tests:
          - unique
    tests:
      - two_tables_change_count:
          threshold: '50'
          other_model: `view_up`
```

and inside the macro:

```
...
with base AS (
   select (
        select count(*)
        from {{ ref(other_model) }}
...
```

My question is:

Is this the intended feature or am I using it wrongly? or is there a command
that could disable the triggering of all downstream healthcheck

### Expected behavior
Not triggering any data tests out side of the model yml definition.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [X] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.19.1
   latest version: 0.19.1

Up to date!

Plugins:
  - bigquery: 0.19.1
  - snowflake: 0.19.1
  - redshift: 0.19.1
  - postgres: 0.19.1

```

**The operating system you're using:**

MacOS 11.1

**The output of `python --version`:**

3.7.6
