### ISSUE TITLE
env_var in profiles.yml fails

### ISSUE THREAD

**Issue by HarlanH** [fishtown-analytics/dbt#513]
Hi, we've confirmed this on two different machines, both running 0.8.3.

My `profiles.yml` file looks (in part) like this:

```
redshift:
  outputs:
    dev:
      type: redshift
      threads: 1
      host: XXXX
      port: XXXX
      user: {{ env_var('REDSHIFT_USER') }}
```

When I run `dbt compile` I get this:

```
$ dbt compile
Encountered an error:

dbt encountered an error while trying to read your profiles.yml file.

Syntax error near line 12
------------------------------
9  |       threads: 1
10 |       host: XXX
11 |       port: XXX
12 |       user: {{ env_var('REDSHIFT_USER') }}
13 |       pass: XXXX
14 |       dbname: segmentevents
15 |       schema: dbt_harlan

Raw Error:
------------------------------
while constructing a mapping
  in "<unicode string>", line 12, column 13:
          user: {{ env_var('REDSHIFT_USER') }}
                ^
found unhashable key
  in "<unicode string>", line 12, column 14:
          user: {{ env_var('REDSHIFT_USER') }}
                 ^
```

Looking at the dbt code, I see that the test suite tests for `env_var` in model files, but I don't see it being tested in YML files? Maybe it worked when this feature was merged, but then a subsequent merge broke it? Or of course, maybe we're doing something wrong? But I don't see what... Ideas?
