### ISSUE TITLE
Spelling errors/typos in schema.sql are not caught

### ISSUE THREAD

**Issue by HarlanH** [fishtown-analytics/dbt#592]
I had misspelled `constraints` as `contraints` for a couple of weeks, and didn't catch it. Expectation is that whatever's parsing the YAML would verify and throw a warning or error if there are fields with unexpected values.

**Comment by HarlanH** [comment]
Oh, OK, yes, that commit helps the specific issue. I think I was thinking about something more general that would throw a warning if you have any YAML clauses that are unknown, with "contraints" being just an example.

**Comment by drewbanin** [comment]
@HarlanH my thinking was that if `constraints` is misspelled as eg. `contraints`, then there would be no `constraints` block and this warning would subsequently fire. I think the only thing that could fall through the cracks here would be:

```yml
model_name:
  constraints:
    unique:
      - id
  contraints:   # typo
    not_null:   #
      - id      # this would be ignored
```

It turns out that `constraints` is the only "special" keyword in here. Test names will currently error if misspelled because they're just looking up a macro under the hood.

Lmk if you think there's something else here that I've missed!
