### ISSUE TITLE
--verbose flag

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#619]
This could be be used as a global flag for a number of purposes:

- details on incremental delete/inserts
- show pre/post-hooks
- Show sampled data for dbt seed
- archival steps
- Schema test failure SQL (good idea @ryantbrennan1)
- etc

**Comment by dwallace0723** [comment]
👍  to this. Particularly useful for incremental model logging

**Comment by tayloramurphy** [comment]
This would help alleviate confusion about why "dbt is taking so long to get started". We run a few `on-run-start` hooks and have a large number of models so it takes a while before it gets to the meat of the dbt run. 

I don't think the Jinja code would have to be written, just some description or name of the current step it's on.

Our dbt_project.yml has 

```
on-run-start:
    - "{{resume_warehouse(var('resume_warehouse', false), var('warehouse_name'))}}"
    - "{{create_udfs()}}"

on-run-end:
    - "{{grant_usage_to_schemas(schema_name, rolename)}}"
    - "{{suspend_warehouse(var('suspend_warehouse', false), var('warehouse_name'))}}"

models:
    pre-hook: "{{ logging.log_model_start_event() }}"
    post-hook: "{{ logging.log_model_end_event() }}"
```

On a dbt run it'd be nice too see something like 

```
dbt run --models date_details
Running with dbt=0.13.1

Parsing Macros, Models, Tests
Running on-run-start hook Resume Warehouse
Running on-run-start hook Create UDFs
Running model pre-hook Logging Start

Found 221 models, 888 tests, 4 archives, 0 analyses, 253 macros, 8 operations, 5 seed files, 114 sources

...
```

I'm not sure where that name / description would get set (maybe in a config somewhere or the jinja itself?
