### ISSUE TITLE
--threads does not override the max number of connections in the default adapter

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#648]
```yml
# ~/.dbt/profiles.yml
default:
  target: dev
  outputs:
    dev:
      type: ...
      threads: 1
```

Invoking dbt with `dbt run --threads 2` will cause an error like:

```
Tried to request a new connection "mode_name" but the maximum number of connections are already allocated!
```

dbt should prefer the `--threads` value if one is given, otherwise fall back to the `threads` option in the active target [here](https://github.com/fishtown-analytics/dbt/blob/d13d85681f3b605681f2c68523a3c10b3242fdbd/dbt/adapters/default/impl.py#L432).

Because this happens in the default adapter, it affects all adapters.
