### ISSUE TITLE
bad archive error when required args are not supplied

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#671]
Error:

```
join() argument must be str or bytes, not 'NoneType'
```

This can be caused by typos in the Archival spec, eg:

```yml
archive:
  # these should be underscores
  - source-schema: public
    target-schema: dbt_archive
...
```

dbt should instead show a more helpful error, ideally linking to the docs
