### ISSUE TITLE
Specify column data types for seed data

### ISSUE THREAD

**Issue by ianterrell** [fishtown-analytics/dbt#703]
I'm trying to load some seed data with date information that looks like this:

| `date_key` | `full_date` | `day_name` | `day_abbrev` | ... |
|--|--|--|--|--|
| 20190101 | 1/1/19 | Tuesday | Tue | ... |
| 20190102 | 1/2/19 | Wednesday | Wed | ... |
| 20190103 | 1/3/19 | Thursday | Thu | ... |

I would like to treat `day_name` and `day_abbrev` as textual data. Unfortunately, Agate is interpreting `Tuesday` and `Tue` as the first Tuesday in the year 0001! This leads to date columns with unusable data.

It looks like Agate has support for specifying `column_types` in the underlying [method](http://agate.readthedocs.io/en/1.6.1/api/table.html#agate.Table.from_csv), and I think this could map to seed config nicely.

Something like the following in `dbt_project.yml`:

```yml
seeds:
  dates:
    enabled: true
    column_types:
      date_key: int
      full_date: date
      day_name: text
      day_abbrev: text
      ...
```
