### ISSUE TITLE
dbt archive for Snowflake

### ISSUE THREAD

**Issue by eogilvy12** [fishtown-analytics/dbt#740]
* unable to archive off of raw data
* once dbt models is materialized as a table, can archive that model

**Comment by drewbanin** [comment]
@eogilvy12 I got this working on our internal Snowflake instance, and I definitely have it running in prod in at least one place.

Do you think this could have happened because the raw data was in a different database than the dbt project? 

eg.
```yml
archive:
    - source_schema: 'STAGING'
      target_schema: 'ANALYTICS_ARCHIVED'
      tables:
        - source_table: 'ORDERS'
          target_table: 'ORDERS_ARCHIVED'
          updated_at: 'updated_at::timestamp_ntz'
          unique_key: 'id'
```

If the `STAGING` schema is in the `RAW` database, but dbt runs against the `TRANSFORM` database, then Snowflake will throw an error.
