### ISSUE TITLE
Option to specify csv file from seeds config

### ISSUE THREAD

**Issue by vaughnkoch** [fishtown-analytics/dbt#795]
Hi, in this config, it would be great to have an option to specify the csv file instead of inferring it from the seed title. That way you could switch the csv file without changing the seed database name (which changes the downstream refs as well).

```
seeds:
  my_project:
    enabled: true
    schema: seed_data
    country_codes:
      # Suggestion to let the source file be explicit
      source_file: 'path/to/actual_csv_file.csv'
```
