### ISSUE TITLE
Docs blocks

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#810]
### Overview

In support of autogenerated dbt project documentation (https://github.com/fishtown-analytics/dbt/issues/375, https://github.com/fishtown-analytics/dbt/issues/790), dbt needs a construct to represent long-form, markdown documentation.

This construct should take the form of a Jinja block, `{% docs %}`. These blocks will contain text that will be interpreted as Markdown, and should be compiled with a sensible context.

### Examples

These docs blocks should be named so that they can be referenced from elsewhere in the dbt project. For example, a model can be documented by building the following docs block:

**models/snowplow/sessions/readme.md**
```
{% docs snowplow_sessions %}

This table contains one record for every session recorded by Snowplow.
A session is itself comprised of pageviews that all occur within 30 minutes
of each other. If more than 30 minutes elapse between pageviews, then a
new session is created. Given the following pageviews:

| session_id | page_view_id | page_title |
| ---------- | ------------ | ---------- |
| abc        | 123          | Home       |
| abc        | 456          | About      |
| abc        | 789          | Home       |

The following sessions will be created:

| session_id | first_page_title | count_pageviews |
| ---------- | ---------------- | --------------- |
| abc        | 123              | 2               |
| abc        | 789              | 1               |

{% enddocs %}

{% docs snowplow_sessions__session_id %}

This column is the unique identifier for a Snowplow session. It is generated by a cookie
then expires after 30 minutes of inactivity.

{% enddocs %}
```

Because these blocks are named, they can be referenced elsewhere in the dbt project, for example, in a `schema.yml` file (https://github.com/fishtown-analytics/dbt/issues/790). Eg:

```yml
snowplow_sessions:
  comment: {{ ref('snowplow_sessions', type='docs') }}
  columns:
    - name: session_id
      comment: {{ ref('snowplow_sessions__session_id', type='docs') }}
```

The linkage between a model schema and documentation can be handled in a couple of ways:
1. Purely on a name basis, as shown above
2. With a `model=` config in the docs block

An example of approach (2) might look like:

```
{% docs model="snowplow_sessions" %}

... docs ...

{% enddocs %}
```

If this approach is used, then it may not be necessary to specify the comment for the model in `schema.yml`. I sort of dislike this approach, as the docs could become fragmented across many different files. I'm definitely open to discussion though.

One other benefit of defining documentation separately from a model definition is that docs can be reused where appropriate. The `session_id` column is used in _many_ places, both inside and outside of the Snowplow package. I _really_ like the idea of being able to use *exactly* the same definition for this column everywhere that it appears. For example:

```yml
# A model in the Snowplow package
snowplow_sessions:
  columns:
    - name: session_id
      comment: {{ ref('snowplow', 'session_id', type='docs') }}

....

# A model in my project
session_attribution:
  columns:
    - name: session_id
      comment: {{ ref('snowplow', 'session_id', type='docs') }}
...
```

### Referencing docs

Above, I used the syntax `{{ ref(package_name, model_name, type) }}`. The two-argument version of `ref` currently exists (package name + model name), but the `type` argument would be new. I think we have a few options:
1. Use `ref`, but add an argument to specify a `type`, as shown above
2. Use `ref`, but infer what types of resources can be referenced by the context of its use
3. Use a different function like `docs(....)` which wraps some underlying implementation of `ref`, but only selects docs nodes. We could call this `ref_docs` if that seems more consistent?

I think that (3) above is my preference, but I am open to discussion.

### Compilation Context

Some dbt concepts map naturally to the docs environment. For example, there's a great opportunity to use macros in docs to eg. reuse a documentation template, generate a markdown table, add links, etc. These macros could conceivably live in a dbt package. Cool!

Other concepts like `ref()` are interesting to consider. I can imagine that if you `{{ ref(...) }}` a model inside of the docs, dbt could compile in `schema.table`, so that the docs would be correct regardless of compilation environment. I can also imagine making it possible to generate _links_ to other dbt models when `ref()` is used. The context available to users during compilation should be sensible and consistent with the model context, to the extent possible. 

cc @jthandy @cmcarthur
