### ISSUE TITLE
Define source tables

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#814]
Related: https://github.com/fishtown-analytics/dbt/issues/790

Presently, the link between source data and dbt models is pretty tenuous. dbt should provide a mechanism for defining source tables, and users should be able to select from these source tables with a mechanism similar to `ref`. Further, these source tables should be documented alongside other dbt resources.

### Proposed Syntax

```yml
sources:
  - name: snowplow
    loader: snowplow # This is new, see below
    loaded_at_field: etl_tstamp # This is new, see below
    description: "A snowplow dataset"
    freshness: # This is new, see below
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
        - name: event
          description: An immutable log of events collected by Snowplow
          loaded_at_field: _etl_tstamp # Override value from top-level source
          sql_table_name: snowplow.event
          columns:
            - name: collector_tstamp
              description: Timestamp for the event recorded by the collector

            - name: domain_userid
              description: User ID set by Snowplow using 1st party cookie
              tests:
                  - unique

        - name: web_page
          description: "{{ docs('snowplow_web_page') }}"
          sql_table_name: "{{ var('snowplow:web_page') }}"
          columns:
            - name: event_id
              description: {{ docs('snowplow_web_page.event_id') }}
```

### Notes
For more information on the `description` and `columns` fields, check out the discussion on the [new schema.yml syntax](https://github.com/fishtown-analytics/dbt/issues/790).

There are two new constructs here:

### sql_table_name

This field will be responsible for pointing to a table in the warehouse. This syntax works for:

**BigQuery**:
 - Syntax: `project-name.dataset.tablename`
 - *can* select across projects

**Snowflake**:
 - Syntax: `database.schema.tablename`
 - *can* select across databases

**pg/Redshift**:
 - Syntax: `schema.tablename`
 - *can not* select across databases. Cross-db references should not however be enforced!

Rather than trying to construct the table name automatically, users will need to enter the exact identifier for the source table.

### loader
This will be used for documentation. Loader can be something like Airflow, Stitch, Fivetran, etc. User supplied.

### loaded_at_field

This field indicates which timestamp field in the source table should be used as the "loaded at" timestamp. This varies by ETL loader, but for loaders which _do_ supply such a field, we can calculate how long ago certain sources were loaded. This field can be specified at the `source` level or at the `table` level. If specified at the `table` level, the value overrides the value from the `source` if present.

### freshness

This field describes the acceptable latency for source tables. This field can be provided at the `source` or `table` level. If provided at the `source` level, it should apply to all of the tables in the source. If provided at the table level, it should override any freshness configuration at the source level. The `freshness` value for a table can be set to `null` to override the value specified in the source.

Acceptable formats:
```
    freshness:
      warn_after:
        count: 12
        period: hour
      error_after:
        count: 24
        period: hour
```

Acceptable periods are `minute`, `hour`, and `day`.

### Usage

To select from a source table, users can use the `source` function, analogous to `ref`. This function accepts two arguments: a source and a table. For example:

```sql
-- models/snowplow/snowplow_sessions_xf.sql

select * from {{ source('snowplow', 'event') }}
```

will render to:

```
select * from snowplow.event
```

When `source()` is used, an edge will be added to the graph. This will allow model selection like: "run everything that depends on Snowplow data". In the above example `snowplow_event` is derived from the `name:` parameter of the first table definition.

Ex:
```
# run all models that touch Snowplow data
$ dbt run --models source:snowplow+
```

See #1014 for info about the selection syntax shown above.

See #1240 for info about model freshness

**Comment by jthandy** [comment]
I like this a lot. I have a couple of questions that popped into my head from reading this that we'll likely have to answer before completing this feature:

- what does the CLI syntax look like for selecting everything that depends on snowplow source tables? I don't think there's a way to do that with `--models` today because our hierarchy there is different...

- what is the name of the file that contains this yaml? `sources.yml`? can there be many of these files? can packages define their own sources which then get namespaced as `packages.source_name.table_name`?

**Comment by cmcarthur** [comment]
this looks great.

the only thing i'm not 100% sure on is `sql_table_name`. this is kind of like `alias`, right? but it also includes a schema, database, or other namespace. i wonder if it's better to define this like other relations, where you can specify a identifier, schema, and/or database. that way when we ref it we already have a relation in place.

so instead of sql_table_name, we'd have:

```yml
sources:
  - name: snowplow
    description: "A snowplow dataset"
    tables:
        - name: snowplow_event
          description: An immutable log of events collected by Snowplow
          schema: snowplow
          identifier: event
          columns:
            - name: collector_tstamp
              description: Timestamp for the event recorded by the collector

            - name: domain_userid
              description: User ID set by Snowplow using 1st party cookie
              tests:
                  - unique

        - name: web_page
          description: "{{ docs('snowplow_web_page') }}"
          # this used to be one var, which is unfortunate! hard to convert.
          # sql_table_name: "{{ var('snowplow:web_page') }}"
          schema: snowplow
          identifier: "{{ var('snowplow:web_page') }}"
          columns:
            - name: event_id
              description: {{ docs('snowplow_web_page.event_id') }}
```
