### ISSUE TITLE
Record failing rows for tests into an auditable table

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#903]
### Feature description
dbt should record rows that fail schema or data tests into tables, to be used for auditing. There are two general ways this could work:

1. insert into an `errors` table with a schema like:
 - run started at
 - invocation id
 - test name
 - failing row primary key / json

2. Create a table for each test failure in a scratch schema, matching the schema of the test query that failed

The baked-in schema tests will need to be rewritten to provide debuggable information in these tables.

This should probably be an opt-in feature for tests. It could be configured either in `schema.yml`, though it would also be good to configure whole swaths of tests at once.

### Who will this benefit?
dbt users could use this table to quickly determine why their tests failed. At present, it's surprisingly difficult to debug a failed test.

**Comment by alanmcruickshank** [comment]
@drewbanin - I totally get that we wouldn't want to bring back all the rows by default, what would be awesome, would be some kind of executable SQL on fail. So the workflow would look like:

1. Run test
2. Evaluate Pass/Fail
3. _[optionally]_ On fail run SQL and spit out the result to logs.

The reason I think this would work nicely is that our analysts are used to looking at the logs of a build to see if something has failed, and having the info right there in the logs would be a massive productivity gain - albeit if there's a config overhead to write in explicitly what should happen on failing for each test.

**Comment by ianterrell** [comment]
I support and would use the use case of reporting on failed tests. I am more interested in using them for auditing than for debugging — I would like a nice easy table to query via Looker for a conditional "Go Fix ETL" alert.

When I went looking to do this feature I naturally reached for hooks, as I'm using them already for audit purposes much as described in the [documentation](https://docs.getdbt.com/docs/using-hooks). 

I'm logging the individual model run:

```yaml
on-run-start:
    - "create table if not exists {{ target.schema }}.audit_dbt_runs (model text, state text, time timestamp)"

models:
  pre-hook:
    - "insert into {{ target.schema }}.audit_dbt_runs (model, state, time) values ('{{this.name}}', 'start', getdate())"
  post-hook:
    - "insert into {{ target.schema }}.audit_dbt_runs (model, state, time) values ('{{this.name}}', 'end', getdate())"
```

As well as the overall results:

```yaml
on-run-start:
    - "create table if not exists {{ target.schema }}.audit_dbt_results (node text, status text, execution_time decimal(10,2), time timestamp)"
on-run-end:
    - "insert into {{ target.schema }}.audit_dbt_results (node, status, execution_time, time) values {{ results_values(results) }}"
```

(I have a simple macro `results_values` to turn the `results` into insertable values.)

In this case I would generally like the exact same thing for tests. Something exactly analogous to the `on-run-start`/`on-run-end` with the end run context `results` would suit my needs:

```yaml
on-test-start:
    - "create table if not exists {{ target.schema }}.audit_dbt_test_results (node text, status text, execution_time decimal(10,2), time timestamp)"
on-test-end:
    - "insert into {{ target.schema }}. audit_dbt_test_results (node, status, execution_time, time) values {{ results_values(results) }}"
```

**Comment by gordonhwong** [comment]
that looks like a great start to a 'dbt_results_mart', where you could have models as a dim, dbt_runs as a dim and fact and errors as an optional fact

**Comment by Aylr** [comment]
@ianterrell This is a great idea. Are you able & willing to share your `results_values` macro?

**Comment by gordonhwong** [comment]
i'd be interested in getting a look at that macro was well.

**Comment by Aylr** [comment]
Here's an easy macro for this.
```
{% macro unpack_results(results) %}

  {% for res in results -%}
-- This is useful for debugging
--     {{ log(res, info=True) }}
        ('{{ invocation_id }}', '{{run_started_at}}', NOW(), '{{ res.node.unique_id }}', '{{ res.status }}', '{{ res.error if res.error != None else ""}}', '{{ res.skip if res.skip != None else "" }}', '{{ res.fail if res.fail != None else "" }}', {{ res.execution_time }} ){{ "," if not loop.last }}
  {% endfor %}

{% endmacro %}
```

**Comment by ianterrell** [comment]
Hi @Aylr and @gordonhwong! 

In case it's still useful for anyone, the following macro is what I use:

```python
{% macro results_values(results) %}
  {% for res in results -%}
    {% if loop.index > 1 %},{% endif %}
    ('{{ res.node.alias }}', '{{ res.status }}', {{ res.execution_time }}, getdate())
  {% endfor %}
{% endmacro %}
```

This pairs with:

```yaml
on-run-start:
    - "create table if not exists {{ target.schema }}.audit_dbt_results (node text, status text, execution_time decimal(10,2), time timestamp)"
on-run-end:
    - "insert into {{ target.schema }}.audit_dbt_results (node, status, execution_time, time) values {{ results_values(results) }}"
```
