### ISSUE TITLE
Nest target files in structure similar to project structure

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/dbt#909]
### Feature description
In my `target/compiled/my_project_name/` and `target/run/my_project_name/` directories, I’d like the sql files generated for my models/tests/data to be nested within folders, so that it matches the structure of my project.

At the moment I get something like:
```
target:
  compiled:
    my_project_name:
      base:
        - base_model1.sql
        - base_model2.sql
      hooks:
        - my_project_name-on-run-end-0.sql
      schema_test:
        - non_null_base_model1_id.sql
      - data_test1.sql
      - data_test2.sql
      - model_with_no_subfolder.sql
      - seed_file1.sql
      - seed_file2.sql
```

I would prefer something like:
```
target:
  compiled:
    my_project_name:
      data:
        - seed_file1.sql
        - seed_file2.sql
      hooks:
        - my_project_name-on-run-end-0.sql
      models:
        - model_with_no_subfolder.sql
        base:
          - base_model1.sql
          - base_model2.sql
      schema_test:
        - non_null_base_model1_id.sql
      tests: #i.e. data tests
        - data_test1.sql
        - data_test2.sql
```

### Who will this benefit?
My OCD self.
