### ISSUE TITLE
Script to convert v1 schema.yml to v2 schema.yml

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#942]
This script shouldn't live in dbt, but it could very well include dbt as a library.

#### Requirements:

The script should:
1. Be run from the root of a dbt_project.yml file
2. Load up all of the `.yml` files in the project's `source-paths` directories
3. Parse and load up all v1 schema specs
4. Convert the v1 schema specs to v2 schema specs
5. Print a small summary of the changes that will be made (number of files and their names)
6. Prompt for confirmation, indicating that the user should check that all of their code is checked in
7. Overwrite the v1 yml file with the v2 spec

#### Caveats:
1. some v1 schema tests do not have immediately obvious representations in the v2 spec

Given:
```
events:
  constraints:
    unique:
      - id
      - "concat(first_name, last_name)"
```

The v2 representation for this schema.yml is:

```
models:
  - name: events
    tests:
      - unique: "concat(first_name, last_name)"

    columns:
      - name: id
        tests:
          - unique
```

Here, the script should determine if the argument to the test is a single field name or an expression. If the argument contains any characters outside of `[a-zA-Z0-9_]`, then the argument should be considered an expression. If the argument is an expression, then it should be translated as a _model_ test instead of a _column_ test. If the argument looks like an identifier, then the script should assume that the identifier is the name of a column. A message should be logged to file indicating that the column could not be determined for the test.

2. Argument inference for custom schema tests

The arguments for the `unique`, `not_null`, `accepted_values` and `relationships` tests are known to dbt. Some projects may contain custom schema tests. An example of a custom schema test might look like:

```
events:
  constraints:
    dbt_utils.recency:
            - {field: created_at, datepart: day, interval: 1}
```

Custom schema tests (ie. not one of the four that ships with dbt) should be created as model tests. A message should be logged to file indicating that the column could not be determined for the test.

#### Interface:
```
./upgrade_dbt_schema_tests_v1_to_v2.py
```

Then script should write log output to a file like `upgrade_dbt_schema_tests_v1_to_v2.txt`
